'use strict';
const assert=require('node:assert/strict');
const {BookState}=require('../assets/course/book-state.js');
const T=BookState.create('tomer-devorah'),B=BookState.create('bahir');
assert.notEqual(T.course,B.course);
assert.throws(()=>BookState.create('yetzirah'));
const old=T.empty();old.lessons['1']={before:'Первый вопрос',working:'Мой черновик <script>',note:'Мысль',done:true};
assert.deepEqual(T.normalize(JSON.parse(JSON.stringify(old))),old);
assert.deepEqual(B.normalize(old),B.empty());
assert.throws(()=>B.merge(B.empty(),old),/этой книги/);
const incoming=T.empty();incoming.lessons['1']={before:'Другое предположение',working:'Мой черновик <script>',note:'',done:false};
incoming.lessons['12']={before:'',working:'Итоговый комментарий',note:'Вопрос',done:true};
const merged=T.merge(old,incoming);
assert(merged.lessons['1'].before.includes('Первый вопрос'));
assert(merged.lessons['1'].before.endsWith('Другое предположение'));
assert.equal(merged.lessons['1'].working,old.lessons['1'].working);
assert.equal(merged.lessons['1'].note,'Мысль');
assert.equal(merged.lessons['1'].done,true);
assert.equal(merged.lessons['12'].working,'Итоговый комментарий');
assert.deepEqual(T.merge(merged,incoming),merged);
assert.equal(old.lessons['1'].before,'Первый вопрос');
const huge=T.empty();huge.lessons['1']={before:'x'.repeat(99999),working:'',note:'',done:false};
assert.throws(()=>T.merge(huge,incoming),/слишком длинная/);
assert.equal(huge.lessons['1'].before.length,99999);
for(const bad of [{...incoming,version:9},{...incoming,lessons:{'13':{}}},{...incoming,lessons:{'1':{note:42}}}])assert.throws(()=>T.merge(old,bad));
const poison=JSON.parse('{"course":"'+T.course+'","version":1,"lessons":{"__proto__":{"polluted":true}}}');
assert.throws(()=>T.merge(old,poison));assert.equal({}.polluted,undefined);
console.log('Book notebooks: independent identities, round-trip, non-destructive/idempotent merge, malformed files and overflow passed.');
