const assert=require('node:assert/strict');
const M=require('../assets/course/mixed-reading-core.js'),G=require('../assets/course/spread-grammar-core.js');
const cards=require('../content/tarot.json').cards,method=require('../content/tarot-pairs.json'),paths=require('../content/pathways.json').paths,D=require('../content/mixed-reading.json');
const model=M.create(cards,method,paths),E=G.create(cards,D.lessons,{app:D.app,title:D.title,layoutIds:D.layoutIds});
assert.equal(D.app,M.APP);assert.equal(D.lessons.length,6);assert.equal(D.lessons.flatMap(l=>l.quiz).length,12);assert.equal(D.checklist.length,6);
for(const l of D.lessons){const c=E.strictConfig(l.default);assert.equal(c.ids.length,G.LAYOUTS[c.layout].n);if(c.layout.startsWith('custom'))assert.deepEqual(c.roles,l.default.roles);assert.equal(model.inspect(c.ids).rows.length,c.ids.length);assert.ok(l.reading.original&&l.reading.url&&l.reading.context);assert.ok(l.refs.every(k=>D.sources[k]));for(const q of l.quiz)assert.ok(q.answer>=0&&q.answer<q.options.length);}
assert.deepEqual(model.inspect(cards.map(c=>c.id)).counts,{number:40,court:16,major:22});assert.deepEqual(model.inspect([]).counts,{number:0,court:0,major:0});assert.throws(()=>model.inspect(['w4','w4']));assert.throws(()=>model.inspect(['unknown']));
for(const p of paths){const info=model.inspect([p.id,...cards.filter(c=>c.group!=='major').map(c=>c.id)]);assert.equal(info.links.length,1);for(const end of info.links[0].endpoints){assert.equal(end.cards.length,4);assert.ok(end.cards.every(c=>c.kind==='number'&&c.rank===end.rank));assert.equal(new Set(end.cards.map(c=>c.world)).size,4);}}
const known=model.inspect(['w4','8','w5','w13']);assert.deepEqual(known.counts,{number:2,court:1,major:1});assert.equal(known.links[0].card.path.number,19);assert.deepEqual(known.links[0].endpoints.map(e=>[e.rank,e.sefira,e.cards.map(c=>c.id)]),[[4,'Хесед',['w4']],[5,'Гвура',['w5']]]);
const changed=model.inspect(['p4','8','w5','w13']);assert.equal(changed.links[0].endpoints[0].cards[0].world,'Асия');assert.equal(changed.links[0].endpoints[1].cards[0].world,'Ацилут');
const noNumbers=model.inspect(['4','14','c13','w11']);assert.equal(noNumbers.counts.number,0);assert.ok(noNumbers.links.every(p=>p.endpoints.every(e=>e.cards.length===0)));assert.equal(model.describe('c13').letterName,'Первая хе');assert.equal(model.describe('w11').letterName,'Последняя хе');assert.equal(model.describe('9').kind,'major');assert.equal(model.describe('9').path.a,4);assert.equal(model.describe('9').path.b,6);
const repeats=model.inspect(['s8','p8','9','s12']);assert.equal(repeats.repeats.length,1);assert.equal(repeats.repeats[0].sefira,'Ход');assert.deepEqual(repeats.repeats[0].cards.map(c=>c.id),['s8','p8']);
const lesson5=model.inspect(D.lessons[4].default.ids);assert.deepEqual(lesson5.repeats.map(x=>x.rank),[3,6]);assert.ok(lesson5.links[0].endpoints.every(e=>e.cards.length===0));const lesson6=model.inspect(D.lessons[5].default.ids);assert.equal(lesson6.links[0].endpoints.filter(e=>e.cards.length).length,1);
for(const layout of D.layoutIds)for(const card of cards)for(let i=0;i<G.LAYOUTS[layout].n;i++){
 const ids=cards.filter(c=>c.id!==card.id).slice(0,G.LAYOUTS[layout].n).map(c=>c.id);ids[i]=card.id;const c=E.normalize({layout,ids,reversed:ids.map((_,j)=>j%2===0),focus:card.id});assert.equal(c.ids[i],card.id);assert.equal(new Set(c.ids).size,c.ids.length);const j=(i+1)%c.ids.length,next=E.swap(c,i,j);assert.equal(next.ids[j],card.id);assert.equal(next.reversed[j],c.reversed[i]);assert.deepEqual(next.roles,c.roles);assert.equal(next.focus,card.id);
}
const config=E.normalize(D.lessons[0].default),note=E.blank(1,config);note.question='Какая форма подходит?';note.reading='Первая гипотеза';note.basis='Кордоверо / таблица / свой вывод';let state=E.empty();state.records[E.key(1,config)]=note;state.snapshots.push({id:'s1',at:'2026-09-15T13:00:00Z',note:E.cleanNote(note)});note.reading='Новая гипотеза';state.observations.push({id:'o1',snapshot:'s1',at:'2026-09-16T13:00:00Z',date:'2026-09-16',facts:'Проверили новую форму',revision:'Требуется уточнение'});state=E.validate(JSON.parse(JSON.stringify(state)));assert.equal(state.snapshots[0].note.reading,'Первая гипотеза');assert.deepEqual(E.merge(state,state),state);assert.throws(()=>E.validate({...state,app:'eliora-tree-reading'}));assert.throws(()=>G.create(cards,D.lessons).validate(state));
const roleConfig={...config,roles:[...config.roles]};roleConfig.roles[0]='Другой вопрос';assert.notEqual(E.key(1,config),E.key(1,roleConfig));assert.notEqual(E.key(1,config),E.key(1,{...config,focus:config.ids[0]}));
console.log('All 78 cards / 40-16-22 types; 22 paths and numerical endpoints; world/rank/role distinctions; repeated ranks; all allowed positions; separate notebook and snapshots passed.');
