const assert=require('node:assert/strict');
const G=require('../assets/course/spread-grammar-core.js'),M=require('../assets/course/spread-dynamics-core.js'),cards=require('../content/tarot.json').cards,D=require('../content/spread-dynamics.json');
const E=G.create(cards,D.lessons,{app:D.app,title:D.title,layoutIds:D.layoutIds}),C=M.create(cards,D.lessons,{title:D.title,layoutIds:D.layoutIds});
const note=l=>({...E.blank(l.id,l.default),question:l.example.question,reading:l.example.reading,basis:l.example.evidence,alternative:l.example.alternative});
assert.equal(D.app,M.APP);assert.equal(D.lessons.length,6);assert.equal(D.lessons.flatMap(l=>l.quiz).length,12);
for(const l of D.lessons){E.strictConfig(l.default);E.cleanNote(l.comparison.note);assert.ok(l.reading.original&&l.reading.context&&l.reading.url);assert.ok(l.refs.every(k=>D.sources[k]));const a=note(l),before=JSON.stringify(a);C.compare(a,l.comparison.note);assert.equal(JSON.stringify(a),before);}
const demo=D.lessons.map(l=>C.compare(note(l),l.comparison.note));
assert.equal(demo[0].positions.filter(p=>p.roleChanged).length,1);assert.equal(demo[0].retained.filter(c=>c.moved).length,0);
assert.equal(demo[1].sameConfiguration,true);assert.ok(demo[1].textChanges.some(c=>c.field==='reading'));
assert.deepEqual(demo[2].retained.filter(c=>c.moved).map(c=>c.id),['p11','c2']);assert.ok(demo[2].positions.every(p=>!p.roleChanged));
assert.deepEqual(demo[3].added.map(c=>c.id),['s4']);assert.deepEqual(demo[3].removed.map(c=>c.id),['w8']);assert.deepEqual(demo[3].retained.filter(c=>c.turned).map(c=>c.id),['c13']);
assert.ok(demo[4].warnings.some(t=>t.includes('Вопрос изменился')));assert.equal(demo[4].sameConfiguration,true);assert.deepEqual(demo[5].retained.filter(c=>c.turned).map(c=>c.id),['p4']);
const a=note(D.lessons[0]),b=structuredClone(a);b.config.reversed[0]=true;const moved=structuredClone(b);moved.config=E.swap(moved.config,0,3);let r=C.compare(b,moved);assert.equal(r.retained.filter(c=>c.moved).length,2);assert.equal(r.retained.filter(c=>c.turned).length,0);assert.equal(r.positions.filter(p=>p.roleChanged).length,0);
const six=structuredClone(a);six.config=E.normalize({...a.config,layout:'custom6'});r=C.compare(a,six);assert.equal(r.positions.length,6);assert.equal(r.added.length,2);assert.equal(r.positions[4].before,null);assert.ok(r.warnings.some(t=>t.includes('число карт')));
const pairA=structuredClone(a);pairA.config=E.normalize({...a.config,layout:'pairs',partition:0});const pairB=structuredClone(pairA);pairB.config.partition=2;r=C.compare(pairA,pairB);assert.equal(r.partitionChanged,true);assert.ok(r.warnings.some(t=>t.includes('пары')));
for(const card of cards){const x=structuredClone(a);x.config=E.normalize({layout:'custom4',ids:[card.id,...cards.filter(c=>c.id!==card.id).slice(0,3).map(c=>c.id)],focus:card.id});const y=structuredClone(x);y.config=E.swap(x.config,0,1);y.config.reversed[1]=true;r=C.compare(x,y);const identity=r.retained.find(c=>c.id===card.id);assert.equal(identity.from,1);assert.equal(identity.to,2);assert.equal(identity.turned,true);assert.equal(r.added.length,0);assert.equal(r.removed.length,0);}
const detail=structuredClone(a);detail.observations[a.config.ids[0]]='Новая деталь';r=C.compare(a,detail);assert.equal(r.retained.filter(c=>c.detailChanged).length,1);assert.equal(r.textChanges.length,0);assert.equal(C.compare(a,a).warnings.length,0);
assert.throws(()=>C.compare({...a,lesson:'unknown'},a));assert.throws(()=>C.compare({...a,config:{...a.config,ids:['x','w1','w2','w3']}},a));
const state=E.empty();state.snapshots=[{id:'a',at:'2026-09-16T10:00:00Z',note:E.cleanNote(a)},{id:'b',at:'2026-09-17T10:00:00Z',note:E.cleanNote(b)}];state.observations=[{id:'o',snapshot:'a',at:'2026-09-17T12:00:00Z',date:'2026-09-16',facts:'Проверили условие',revision:'Потребовалось уточнение'}];const frozen=JSON.stringify(state);C.compare(state.snapshots[0].note,state.snapshots[1].note);assert.equal(JSON.stringify(state),frozen);assert.deepEqual(E.merge(state,state),E.validate(state));assert.throws(()=>E.validate({...state,app:'eliora-reversal-study'}));
console.log('Six paired lessons, movement vs orientation for all 78 cards, replacement, role/question/layout/partition changes, different sizes and immutable snapshots passed.');
