'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const P=require('../assets/course/tarot-pairs-core.js');
const cards=JSON.parse(fs.readFileSync(path.join(root,'content/tarot.json'))).cards;
const data=JSON.parse(fs.readFileSync(path.join(root,'content/tarot-pairs.json')));
const combos=[['pair',false,3003],['sequence',false,6006],['pair',true,12012],['sequence',true,24024]];
for(const [order,reversals,total] of combos){
  assert.equal(P.count(order,reversals),total);
  const found=new Set();
  for(let i=0;i<total;i++){
    const s=P.pairAt(i,{order,reversals},cards);
    assert.notEqual(s.a,s.b);
    assert.equal(P.indexOf(s,cards),i);
    assert.deepEqual(P.reverse(P.reverse(s,cards),cards),s);
    found.add(P.key(s,cards));
    const a=P.analyze(s,cards,data);
    assert.ok(a.frame.length>30 && a.structure.text && a.suits.text);
    assert.ok(!JSON.stringify(a).includes('undefined'));
    if(order==='pair')assert.deepEqual(P.analyze({...s,a:s.b,b:s.a,ra:s.rb,rb:s.ra},cards,data),a);
  }
  assert.equal(found.size,total);
  assert.equal(P.indexOf(P.pairAt(total,{order,reversals},cards),cards),0);
  assert.equal(P.indexOf(P.pairAt(-1,{order,reversals},cards),cards),total-1);
  console.log(order+(reversals?' with reversals':'')+': '+total+' unique variants; complete round trip and analysis passed');
}
const s=P.normalize({a:'1',b:'p8',order:'sequence',reversals:true,ra:true,rb:false,lens:'resource'},cards);
const reversed=P.reverse(s,cards);
assert.equal(reversed.b,'1');assert.equal(reversed.rb,true);assert.equal(reversed.ra,false);
assert.notEqual(P.key(s,cards),P.key(reversed,cards));
assert.notEqual(P.key(s,cards),P.key({...s,lens:'obstacle'},cards));
const analysis=P.analyze(s,cards,data);
assert.equal(analysis.a.major.name,'Бет');assert.equal(analysis.a.sefira,undefined);
assert.equal(analysis.b.sefira.name,'Ход');assert.equal(analysis.b.suit.world,'Асия');
assert.equal(P.cardMeta(cards.find(c=>c.id==='8'),data).major.name,'Тет');
assert.equal(P.cardMeta(cards.find(c=>c.id==='11'),data).major.name,'Ламед');
assert.equal(P.cardMeta(cards.find(c=>c.id==='p14'),data).sefira,undefined);
assert.match(P.analyze({a:'s2',b:'p2'},cards,data).structure.title,/Одна сефира/);
assert.match(P.analyze({a:'s2',b:'p2'},cards,data).suits.title,/Противоположные/);
assert.match(P.analyze({a:'c2',b:'p2'},cards,data).suits.title,/не задаёт/);
assert.match(P.analyze({a:'1',b:'p2'},cards,data).suits.title,/не вычисляем/);
const note=P.emptyNote(s);note.question='Как учиться?';note.connection='Практика поддерживает действие.';note.checks=['images'];
const k=P.key(s,cards);
const original=P.readNotebook({app:'eliora-tarot-pairs',version:1,notes:[note]},cards);
assert.equal(original[k].question,note.question);
assert.equal(P.readNotebook(JSON.parse(JSON.stringify({app:'eliora-tarot-pairs',version:1,notes:Object.values(original)})),cards)[k].connection,note.connection);
const incoming=structuredClone(note);incoming.connection='Осмысленное действие задаёт направление практике.';incoming.checks=['positions'];
const merged=P.mergeNotes(original,{[k]:incoming});
assert.ok(merged[k].connection.includes(note.connection));assert.ok(merged[k].connection.includes(incoming.connection));
assert.equal(original[k].connection,note.connection,'merge must not mutate existing records');
assert.equal(P.mergeNotes(merged,{[k]:incoming})[k].connection,merged[k].connection,'reimport is idempotent');
assert.deepEqual(merged[k].checks,['images','positions']);
assert.throws(()=>P.readNotebook({app:'other',version:1,notes:[]},cards));
assert.throws(()=>P.readNotebook({app:'eliora-tarot-pairs',version:1,notes:[{...note,state:{...s,a:s.b}}]},cards));
assert.throws(()=>P.readNotebook({app:'eliora-tarot-pairs',version:1,notes:[{...note,question:{}}]},cards));
const large={...note,connection:'A'.repeat(6000)};
assert.throws(()=>P.mergeNotes({[k]:large},{[k]:{...note,connection:'B'.repeat(6000)}}));
assert.equal(large.connection.length,6000);
const swappedNote={...note,state:{...s,order:'pair',a:'p8',b:'1',ra:false,rb:true},observationA:'Практика',observationB:'Средства',conditionA:'lack',conditionB:'excess'};
const canonical=P.cleanNote(swappedNote,cards);
assert.equal(canonical.state.a,'1');assert.equal(canonical.observationA,'Средства');assert.equal(canonical.conditionA,'excess');
const duplicates=P.readNotebook({app:'eliora-tarot-pairs',version:1,notes:[note,incoming]},cards);
assert.ok(duplicates[k].connection.includes(note.connection)&&duplicates[k].connection.includes(incoming.connection));
console.log('Correspondence boundaries, orientation identity, note separation, export/import and non-destructive merge passed.');
