const assert=require('node:assert/strict');
const {YetzirahState:S}=require('../assets/course/yetzirah-state.js');
assert.equal(S.countPairs(22),231);assert.equal(S.countPairs(22,true),462);assert.equal(S.countPairs(4),6);
assert.equal(S.factorial(3),6);assert.equal(S.factorial(4),24);assert.equal(S.factorial(7),5040);
const old=S.empty();old.lessons[1]={before:'Моё первое предположение',note:'Старая запись',done:true,quiz:{0:1}};
old.lessons[12]={before:'',note:'Итоговый комментарий',done:false,quiz:{}};
const incoming={course:'eliora-yetzirah-v1',version:1,lessons:{1:{before:'Моё первое предположение',note:'Другая мысль',done:false,quiz:{0:2}},2:{before:'Новый вопрос',note:'',done:true}}};
const merged=S.merge(old,incoming);
assert.equal(merged.lessons[1].before,old.lessons[1].before);
assert.ok(merged.lessons[1].note.includes('Старая запись'));assert.ok(merged.lessons[1].note.includes('Другая мысль'));
assert.equal(merged.lessons[1].done,true);assert.equal(merged.lessons[1].quiz[0],1);
assert.equal(merged.lessons[12].note,'Итоговый комментарий');assert.equal(merged.lessons[2].done,true);
assert.deepEqual(S.merge(merged,incoming),merged);assert.equal(old.lessons[1].note,'Старая запись');
assert.deepEqual(S.normalize(JSON.parse(JSON.stringify(merged))),merged);
assert.throws(()=>S.merge(old,{course:'eliora-kabbalah-v2',version:2,lessons:{}}));
assert.throws(()=>S.merge(old,{...incoming,lessons:{1:{note:42}}}));
assert.throws(()=>S.merge(old,{...incoming,lessons:{13:{note:'unknown'}}}));
assert.deepEqual(S.normalize({course:'other',version:1,lessons:{1:{done:true}}}),S.empty());
console.log('Yetzirah: pair and permutation counts, independent notebook, round trip, conflict-preserving import and rejection of invalid imports passed.');
