"""Static reading library and Tarot workbench. Called by build_course.py."""
from pathlib import Path
from html import escape as E
import json
ROOT=Path(__file__).resolve().parents[1]
READ=json.loads((ROOT/'content/readings88.json').read_text());TAROT=json.loads((ROOT/'content/tarot.json').read_text());CARDS={x['id']:x for x in TAROT['cards']}
def textp(s):return '<p>'+E(s)+'</p>'
def card(c,full=True):
 return f'<article class="tarot-card" id="card-{c["id"]}" data-search-item="cards" data-card-group="{c["group"]}" data-card-rank="{c["rank"]}"><a class="card-picture" href="{E(c["imageSource"])}" target="_blank" rel="noopener noreferrer"><img loading="lazy" width="120" height="208" src="{E(c["image"])}" alt="{E(c["name"])} — Памела Колман Смит"></a><div><p class="eyebrow">'+('Старший аркан '+str(c['rank']) if c['group']=='major' else ('Придворная карта' if c['rank']>10 else 'Числовая карта · '+str(c['rank'])))+f'</p><h3>{E(c["name"])}</h3>'+textp(c['scene'])+('<p><strong>Учебное прочтение.</strong> '+E(c['reading'])+'</p><p class="card-question">'+E(c['question'])+'</p><a class="fine" href="'+E(c['source'])+'" target="_blank" rel="noopener noreferrer">Сопоставить с руководством Уэйта ↗</a>' if full else '')+'</div></article>'
def gematria():
 vals=list(range(1,10))+list(range(10,100,10))+list(range(100,500,100));letters='אבגדהוזחטיכלמנסעפצקרשת'
 return '<div class="lab" data-gematria><h3>Сложим значения букв</h3><p>Обычная гематрия. Конечные формы сохраняют основное значение; огласовки не считаются.</p><label for="gematria-word">Слово на иврите</label><input class="search hebrew-input" id="gematria-word" dir="rtl" lang="he" maxlength="100" value="חי" autocomplete="off"><div class="chips">'+''.join(f'<button type="button" data-gematria-example="{w}">{w} — {t}</button>' for w,t in [('חי','жизнь'),('אחד','один'),('אהבה','любовь')])+'</div><p class="gematria-result" role="status" data-gematria-output>חי: 8 + 10 = 18</p><details class="example"><summary>Таблица значений</summary><div class="letter-values">'+''.join(f'<span><b lang="he">{c}</b> {v}</span>' for c,v in zip(letters,vals))+'</div><p>ך = 20, ם = 40, ן = 50, ף = 80, ץ = 90.</p></details></div>'
def study(L):
 pair_link='<p><a class="button" href="../tarot-pairs/">Конструктор всех пар: соответствия, порядок и своя запись →</a></p>' if L['slug']=='two-cards' else ''
 s='<div class="lab"><h3>Работаем с изображением</h3>'+textp(L['practice'])+'<div class="tarot-grid lesson-cards">'+''.join(card(CARDS[k]) for k in L.get('cards',[]))+'</div><p><a href="../tarot/#compare">Открыть сравнение двух карт →</a> · <a href="../tarot/#cards">Все 78 карт →</a></p>'
 s+=pair_link
 if L['slug']=='three-cards':
  s+='<p><a class="button" href="../tarot-triples/">Все тройки: каббалистический разбор, шесть порядков и своя запись →</a></p>'
 if L['slug']=='tarot-sefirot':
  rows=list(zip(['Туз','Двойка','Тройка','Четвёрка','Пятёрка','Шестёрка','Семёрка','Восьмёрка','Девятка','Десятка'],['Кетер','Хохма','Бина','Хесед','Гвура','Тиферет','Нецах','Ход','Йесод','Малхут']))
  s+='<div class="table-scroll"><table><caption>Числовые карты и сефирот в западной герметической схеме</caption><thead><tr><th>Ранг во всех четырёх мастях</th><th>Сефира</th></tr></thead><tbody>'+''.join('<tr><td>'+a+'</td><td>'+b+'</td></tr>' for a,b in rows)+'</tbody></table></div>'
 if L['slug']=='tarot-worlds':
  s+='<div class="table-scroll"><table><caption>Распространённое западное соответствие</caption><thead><tr><th>Масть</th><th>Стихия</th><th>Мир</th><th>Буква</th></tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+x+'</td>' for x in row)+'</tr>' for row in [('Жезлы','Огонь','Ацилут','י'),('Кубки','Вода','Брия','ה'),('Мечи','Воздух','Йецира','ו'),('Пентакли','Земля','Асия','ה')])+'</tbody></table></div>'
 return s+'</div>'
def readingcard(r,g,prefix=''):
 link=g['url']+('#page='+str(r['page']) if g['direct'] else '')
 return f'<article class="reading-card" id="reading-{r["id"]:02d}" data-reading-id="{r["id"]}" data-search-item="readings"><p class="eyebrow">Фрагмент {r["id"]:02d} из 88 · {E(g["title"])}</p><h2>{E(r["title"])}</h2><blockquote class="quote">{E(r["quote"])}</blockquote><p class="fine">Цитата из русской редакции «Зоар с комментарием „Сулам“». {E(g["chapter"])} · § {r["paragraph"]} · страница PDF {r["page"]}. </p><h3>Что здесь происходит</h3>'+textp(r['explanation'])+'<h3>Ваш вопрос к тексту</h3>'+textp(r['question'])+f'<p><a href="{E(link)}" target="_blank" rel="noopener noreferrer">'+('Открыть параграф в PDF ↗' if g['direct'] else 'Открыть сайт русского издания ↗')+'</a></p><p class="fine">Файл: '+E(g['file'])+'. Прочитайте весь параграф и соседние строки: короткая цитата — точка входа в текст.</p><details class="example"><summary>Записать мысль к фрагменту</summary><label class="reflection-label" for="reading-note-'+str(r['id'])+'">Моя мысль, наблюдение или возражение</label><textarea class="note" maxlength="20000" data-reading-note="'+str(r['id'])+'" id="reading-note-'+str(r['id'])+'"></textarea><small data-reading-status="'+str(r['id'])+'" role="status"></small></details><label class="self-check"><input type="checkbox" data-reading-done="'+str(r['id'])+'"> Я прочитал(а) параграф и обдумал(а) вопрос</label></article>'
def build(page,crumbs,D,lessonlist):
 groups=READ['groups'];readings=READ['readings']
 hub=crumbs('../../','888 встреч с Зоаром')+'<header class="hero-small"><p class="eyebrow">Одна цитата — начало разговора</p><h1>888 встреч с Зоаром</h1><p class="lead">Большая подборка для неспешного чтения. Можно искать знакомое слово, идти по теме или открыть один из первых 88 подробных разборов.</p><p>В каталоге — 888 коротких фрагментов из русских изданий Зоара с комментарием «Сулам». Первые 88 сопровождаются пояснениями и вопросами курса; ещё 800 — приглашения самостоятельно открыть книгу по указанному месту.</p><div class="actions"><a class="button" href="catalog/">Все 888 фрагментов: найти свою строку →</a><a class="button secondary" href="#guided">Начать с 88 разборов</a></div><p class="fine">В выбранных редакциях текст Зоара и комментарий соседствуют. Подпись к цитате указывает на русское издание; для понимания важно читать весь нумерованный пункт. Число 888 — размер подборки.</p><p><a href="../books/#zohar">Если Зоар пока совсем незнаком</a> · <a href="#sources">Книги и источники</a> · <a href="all/">Поиск по 88 разборам</a></p><p class="reading-progress" data-reading-progress data-reading-limit="888">Прочитано 0 из 888</p></header><section id="guided"><h2>88 встреч с пояснениями</h2><p>Одиннадцать тем по восемь фрагментов: читаем, разбираем и записываем свой вопрос.</p></section><section class="reading-topics">'
 for g in groups:
  rs=[r for r in readings if r['group']==g['id']]
  hub+='<article class="topic-card"><span class="eyebrow">'+f'{rs[0]["id"]:02d}–{rs[-1]["id"]:02d}'+'</span><h2><a href="'+g['id']+'/">'+E(g['title'])+'</a></h2>'+textp(g['intro'])+'<a href="'+g['id']+'/">Открыть восемь фрагментов →</a></article>'
  body=crumbs('../../../',g['title'])+'<header class="hero-small"><p class="eyebrow">Читаем Зоар · 8 встреч</p><h1>'+E(g['title'])+'</h1><p class="lead">'+E(g['intro'])+'</p><p class="fine">Читаем русскую редакцию Зоара с комментарием «Сулам». В цитатах могут звучать и слова комментария; пояснения и вопросы написаны для курса.</p><p><a href="../">Все темы</a> · <a href="../../notebook/#reading-notes">Мои записи к Зоару</a></p><p data-reading-progress>Прочитано 0 из 88</p></header>'+''.join(readingcard(r,g) for r in rs)
  i=groups.index(g)
  body+='<nav class="next-prev">'+('<a href="../'+groups[i-1]['id']+'/">← '+E(groups[i-1]['title'])+'</a>' if i else '<a href="../">← Все темы</a>')+('<a href="../'+groups[i+1]['id']+'/">'+E(groups[i+1]['title'])+' →</a>' if i<len(groups)-1 else '<a href="../../notebook/#reading-notes">К своим записям →</a>')+'</nav>'
  page('/course/reading/'+g['id']+'/',g['title']+' — чтение Зоара',g['intro'],body)
 hub+='</section><section class="section"><h2>Как провести одну встречу</h2><ol><li>Прочитайте цитату и откройте весь параграф по указанному месту.</li><li>Назовите непонятное слово. Посмотрите его в словаре или введении о книгах.</li><li>Перечитайте пояснение, затем ответьте на вопрос своим примером.</li><li>Если хочется сопоставить с Таро, выберите карту и объясните связь через детали обоих источников.</li></ol><p>Для первого сравнения подойдут помощь бедному из последней подборки и Шестёрка пентаклей. В Зоаре речь о заповеди и человеческом образе; на карте видны даритель, весы и получающие. Что каждый источник добавляет к разговору о помощи?</p><a href="../tarot/#card-p6">Рассмотреть Шестёрку пентаклей →</a></section><section id="sources" class="section"><h2>Книги и источники</h2><div class="catalogue">'
 for src in D['sources'].values():hub+='<article class="book"><p class="source-tag">'+E(src['type'])+'</p><h3>'+E(src['title'])+'</h3>'+textp(src['detail'])+'<a href="'+E(src['url'])+'" target="_blank" rel="noopener noreferrer">Открыть источник ↗</a></article>'
 hub+='</div></section>'
 page('/course/reading/','888 встреч с Зоаром — цитаты и чтение','888 фрагментов русских изданий Зоара с Сулам: каталог с поиском и темами, 88 разборов, источники и личные записи.',hub)
 allbody=crumbs('../../../','Все 88 цитат')+'<header class="hero-small"><h1>Найти свою строку</h1><p class="lead">Все 88 фрагментов в одном месте. Ищите образ, тему или слово из цитаты.</p><label for="reading-search">Что ищем?</label><input class="search" type="search" id="reading-search" data-search="readings" placeholder="Например, буквы или милосердие"><span data-search-status="readings" role="status"></span><p><a href="../#guided">Вернуться к одиннадцати темам</a> · <a href="../catalog/">Открыть каталог 888 фрагментов</a></p><p data-reading-progress>Прочитано 0 из 88</p></header>'
 allbody+=''.join(readingcard(r,next(g for g in groups if g['id']==r['group'])) for r in readings)
 page('/course/reading/all/','Все 88 фрагментов Зоара — поиск','Поиск по цитатам, пояснениям и вопросам к Зоару. Можно записать отклик рядом с каждым фрагментом.',allbody)
 # A calm Tarot landing with all cards readable without JavaScript.
 b=crumbs('../../','Изучаем Таро')+'<header class="hero-small"><p class="eyebrow">Можно начать здесь</p><h1>Таро: смотреть, понимать, читать</h1><p class="lead">У карт есть рисунок, история и характер движения. Будем узнавать их постепенно: через сравнение, небольшие расклады и собственные вопросы.</p><p>Основная колода — Уэйт–Смит, рисунки Памелы Колман Смит. Ниже — все 78 карт с наблюдениями и учебными прочтениями курса. Изображение можно открыть крупнее по ссылке; его цвета могут различаться между изданиями.</p><div class="actions"><a class="button" href="../tarot-culture/">Начать с песни и туза →</a><a class="button secondary" href="#compare">Сравнить две карты</a><a href="#cards">Найти карту</a></div></header><section class="section"><h2>Двадцать встреч с Таро</h2>'
 b+=lessonlist([l for l in D['lessons'] if 25<=l['id']<=44],'../../')+'</section><section class="section" id="compare"><h2>Что происходит между двумя картами?</h2><p>Выберите пару. Назовите действие каждой карты, затем соедините их одной фразой. Поменяйте порядок и посмотрите, как меняется история.</p><div class="compare-controls">'
 for i in [0,1]:b+=f'<label for="compare-{i}">'+('Первая карта' if i==0 else 'Вторая карта')+f'</label><select id="compare-{i}" data-compare="{i}">'+''.join('<option value="'+c['id']+'"'+(' selected' if c['id']==['1','p8'][i] else '')+'>'+E(c['name'])+'</option>' for c in TAROT['cards'])+'</select>'
 b+='<button class="button secondary" type="button" data-swap-cards>Поменять местами</button></div><div class="tarot-grid" data-compare-result>'+card(CARDS['1']).replace(' id="card-1"','')+card(CARDS['p8']).replace(' id="card-p8"','')+'</div><p><a href="../two-cards/">Пример чтения пары и место для своей записи →</a></p></section><section class="section" id="cards"><h2>Все 78 карт</h2><label for="card-search">Название, деталь или вопрос</label><input class="search" type="search" id="card-search" data-card-search placeholder="Например, Луна, пятёрка, работа"><div class="compare-controls"><label for="card-group">Группа</label><select id="card-group" data-card-filter><option value="all">Все карты</option>'+''.join('<option value="'+k+'">'+v+'</option>' for k,v in [('major','Старшие арканы'),('w','Жезлы'),('c','Кубки'),('s','Мечи'),('p','Пентакли'),('court','Придворные')])+'</select><label for="card-rank">Число в четырёх мастях</label><select id="card-rank" data-rank-filter><option value="all">Любое число или ранг</option>'+''.join(f'<option value="{n}">{n}</option>' for n in range(1,11))+'</select><button type="button" class="button secondary" data-clear-card-filters>Сбросить</button></div><p role="status" data-card-count>Показано 78 карт</p><div class="tarot-grid" data-card-catalogue>'+''.join(card(c) for c in TAROT['cards'])+'</div></section><section class="section"><h2>Буквы и числа</h2><p>Гематрия, ранги карт и сефирот связаны по-разному. В отдельном уроке разберём расчёт по буквам и научимся не путать эти операции.</p><a href="../gematria/">Перейти к гематрии →</a></section><p class="fine">Источники изображений: Wikimedia Commons, исходные рисунки Памелы Колман Смит для колоды Уэйта–Смит (1909). Ссылка на карточке ведёт к файлу и сведениям о нём. Наблюдения и вопросы написаны для этого курса; традиционные описания можно сопоставить с The Pictorial Key to the Tarot Уэйта (1910).</p>'
 b=b.replace('<div class="compare-controls">','<p><a class="button" href="../tarot-pairs/">Конструктор всех пар и последовательностей →</a></p><p><a class="button" href="../tarot-triples/">Конструктор всех троек: что меняет третья карта →</a></p><p><a class="button secondary" href="../spread-grammar/">Искусство расклада: отдельный модуль с каббалистической опорой →</a></p><p>Каббалистические соответствия, вопросы к связи карт, прямые и перевёрнутые положения, собственные записи.</p><div class="compare-controls">',1)
 b+='<section class="section" id="tarot-book-studies"><h2>Разбираем книги о каббалистическом Таро</h2><p>У Форчун учимся читать Древо и различать сефирот, пути и масти. У Кроули разбираем устройство Тота, сравниваем соответствия и пишем собственный комментарий к трём картам.</p><p><a href="/course/mystical-qabalah/">Мистическая Каббала →</a> · <a href="/course/book-of-thoth/">Книга Тота →</a> · <a href="/course/book-studies/">Все три новых модуля →</a></p></section>'
 page('/course/tarot/','Изучаем Таро — 78 карт и 20 новых занятий','Старшие арканы, четыре масти, придворные карты, сравнение пары, расклады и каббалистические соответствия. Уроки Элиоры Вейры.',b)

