"""Build source-attributed workshops on Gikatilla, Fortune, and Crowley."""
from pathlib import Path
from html import escape as E
import json
ROOT=Path(__file__).resolve().parents[1]
BOOKS=[json.loads((ROOT/'content'/(s+'.json')).read_text()) for s in ['shaarei-orah','mystical-qabalah','book-of-thoth','pardes-rimmonim','tanya']]
def base(d):return '/course/'+d['book']+'/'
def link(d,l):return base(d)+l['slug']+'/'
def p(text):return '<p>'+E(text)+'</p>'
def button(text,attrs='',secondary=False):return f'<button type="button" class="button {"secondary" if secondary else ""}" disabled data-book-enhanced {attrs}>{E(text)}</button>'
def payload(d,l=None):
 x={k:d[k] for k in ['book','title']};x['lessons']=[{k:a[k] for k in ['id','slug','title']} for a in d['lessons']];x['current']=l['id'] if l else 0
 if l:x.update(quiz=l['quiz'],lab=l['lab'])
 return '<script id="book-module-data" type="application/json">'+json.dumps(x,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')+'</script>'
def progress(d):return '<div class="sy-progress"><progress max="'+str(len(d['lessons']))+'" value="0" aria-label="Прогресс модуля" data-book-bar></progress><span data-book-progress>Пройдено 0 из '+str(len(d['lessons']))+' занятий</span></div>'
def field(name,label,rows=4):
 return f'<label for="book-{name}">{E(label)}</label><textarea id="book-{name}" data-book-field="{name}" disabled data-book-enhanced rows="{rows}" maxlength="100000" aria-describedby="book-save-{name}" placeholder="Ваша мысль или вопрос"></textarea><small id="book-save-{name}" data-book-saved="{name}" role="status"></small>'
def solution(text,title='Разобрать задание'):return '<details class="sy-solution"><summary>'+E(title)+'</summary>'+p(text)+'</details>'
def sources(d,l=None):
 s='<section class="sy-source" id="sources"><h2>Источник и способ чтения</h2><p><a href="'+d['source']['url']+'" target="_blank" rel="noopener noreferrer">'+E(d['source']['title'])+' →</a></p>'+p(d['source']['detail'])
 if l:s+='<ul>'+''.join('<li><a href="'+x['url']+'" target="_blank" rel="noopener noreferrer">'+E(x['label'])+'</a></li>' for x in l['refs'])+'</ul>'
 s+=p('Русские пояснения, ситуации и упражнения написаны для проекта Элиоры Вейры. Это учебный комментарий к выбранным местам, а не перевод всей книги. Исторический источник, система автора и наши аналогии обозначены отдельно.')
 return s+'</section>'
def table(headers,rows,caption):
 return '<div class="sy-table-scroll"><table><caption>'+E(caption)+'</caption><thead><tr>'+''.join('<th scope="col">'+E(t)+'</th>' for t in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(('<th scope="row">'+E(t)+'</th>') if i==0 else '<td>'+E(t)+'</td>' for i,t in enumerate(r))+'</tr>' for r in rows)+'</tbody></table></div>'
def contextual_map(d,l):
 if 'table' not in l:return ''
 t=l['table'];return table(t['headers'],t['rows'],t['caption'])
def lab(d,l):
 k=l['lab'];s='<section id="practice" class="sy-lab"><p class="eyebrow">Работа с текстом</p><h2>'+('Ситуация и выбор' if k['type']=='case' else 'Попробуем разобраться')+'</h2>'+p(k['lead'])+contextual_map(d,l)
 if k['type']=='case':
  s+='<p class="book-scenario">'+E(k['scenario'])+'</p><div class="book-choices">'+''.join(button(o['title'],f'data-case-option="{i}" aria-pressed="false"',True) for i,o in enumerate(k['options']))+'</div><div class="book-case-output" data-case-output role="status">Выберите ответ, чтобы посмотреть его последствия. Можно сравнить все варианты.</div>'
  s+=solution(' '.join(o['title']+': '+o['feedback'] for o in k['options']),'Все варианты с пояснениями')
 elif k['type']=='layers':
  if k.get('figure')=='vessels':s+='<figure class="pardes-vessel"><svg viewBox="0 0 520 120" role="img" aria-label="Учебная модель: источник света, окрашенное стекло и видимый цвет"><path d="M45 60H470" stroke="#b89c57" stroke-width="8"/><circle cx="55" cy="60" r="28" fill="#e4ddc7"/><rect x="230" y="15" width="45" height="90" rx="8" fill="#e4ddc7" data-pardes-filter/><circle cx="460" cy="60" r="28" fill="#e4ddc7" data-pardes-filter/></svg><figcaption>Нажмите на варианты ниже. Цвет меняется в учебном рисунке; это наглядная аналогия, а не изображение божественной сущности.</figcaption></figure>'
  s+='<div class="sy-actions">'+''.join(button(o['title'],f'data-layer="{i}" aria-pressed="false"',True) for i,o in enumerate(k['layers']))+'</div><p class="sy-output" data-layer-output role="status">Нажмите на слой объяснения.</p>'+solution(' '.join(o['title']+': '+o['text'] for o in k['layers']),'Все слои объяснения')
 elif k['type']=='match':
  s+='<fieldset class="sy-match" disabled data-book-enhanced><legend>Соберите соответствия</legend>'
  for i,x in enumerate(k['items']):s+=f'<div class="sy-match-row"><label for="book-match-{i}">{E(x["prompt"])}</label><select id="book-match-{i}" data-answer="{E(x["answer"],quote=True)}" aria-describedby="book-match-result-{i}"><option value="">Выберите…</option>'+''.join('<option>'+E(o)+'</option>' for o in x['options'])+f'</select><small id="book-match-result-{i}"></small></div>'
  s+=button('Проверить соответствия','data-book-match-check')+'<p data-book-match-status role="status"></p></fieldset>'
 elif k['type']=='order':
  # Rotate instead of showing the solution order. Each control remains keyboard accessible.
  order=list(range(1,len(k['steps'])))+[0]
  s+='<fieldset disabled data-book-enhanced data-book-order><legend>Выбирайте шаги в нужном порядке</legend><div class="book-choices">'+''.join(button(k['steps'][i],f'data-order-step="{i}"',True) for i in order)+'</div><p class="sy-output" data-order-result role="status"></p><p data-order-feedback role="status"></p>'+button('Начать заново','data-order-reset',True)+'</fieldset>'
 elif k['type']=='gematria':
  s+='<fieldset disabled data-book-enhanced data-gematria><legend>Два написания имени</legend><div class="sy-actions">'+button('Аврам · אברם','data-gematria-name="short" aria-pressed="true"')+button('Авраам · אברהם','data-gematria-name="full" aria-pressed="false"',True)+'</div><p class="sy-formula" data-gematria-output role="status" dir="ltr">אברם: 1 + 2 + 200 + 40 = 243</p></fieldset>'
 elif k['type']=='criteria':s+='<ul class="sy-rubric">'+''.join('<li>'+E(x)+'</li>' for x in k['criteria'])+'</ul>'
 else:raise ValueError(k['type'])
 s+='<div class="book-draft"><h3>Мой черновик</h3>'+field('working',k['task'],5)+solution(k['solution'])+'</div><noscript><p>Для кнопок и записи нужен JavaScript. Текст, источники и разбор задания можно читать без него.</p></noscript></section>'
 return s
def module_card(d):return '<article class="sy-card"><p class="eyebrow">8 занятий · 16 вопросов</p><h2><a href="'+base(d)+'">'+E(d['title'])+'</a></h2><p>'+E(d['subtitle'])+'</p>'+p(d['lead'])+'<a class="button secondary" href="'+base(d)+'">Открыть модуль →</a></article>'
def build(page,crumbs):
 b=crumbs('../../','Продолжаем читать книги')+'<div class="book-modules-main"><header class="sy-hero"><p class="eyebrow">Пять книг · 40 занятий</p><h1>Книги каббалы<br>и каббалистического Таро</h1><p class="lead">Гикатила учит читать связи божественных имён. Форчун строит герметическую карту. Кроули применяет свою систему к конкретной колоде. Кордоверо учит ставить вопросы, сопоставлять объяснения и читать схемы. «Тания» помогает различать силы души, их выражение и внутреннюю работу. Пройдём этот путь с книгами в руках.</p></header><section class="book-module-map">'+''.join(module_card(d) for d in BOOKS)+'</section><section class="sy-route-note"><h2>С чего начать</h2><p>Для последовательного чтения: «Шаарей Ора», затем «Мистическая Каббала», после — «Книга Тота». «Пардес римоним» удобно читать после знакомства с сефирот: это восемь встреч с выбранными главами. Каждый модуль можно открыть отдельно. Знание еврейского или английского языка для первого прохода не требуется: нужный смысл объяснён по-русски, рядом указан раздел оригинала.</p><p>На каждом занятии: первый вопрос, подробное объяснение, исследование, два вопроса с обратной связью и собственная запись. Ориентир — 20–35 минут. В конце модуля Вы соберёте свой комментарий.</p><p><a href="/course/study-tools/">Мастерские чтения →</a> · <a href="/course/books/">Все книги курса →</a> · <a href="/course/yetzirah/">Сефер Йецира →</a> · <a href="/course/reading/">Чтение Зоара →</a></p></section></div>'
 page('/course/book-studies/','Каббалистические книги и книги о Таро — пять модулей','Шаарей Ора, Мистическая Каббала, Книга Тота, Пардес римоним и Тания: 40 занятий, упражнения, 80 вопросов и пять тетрадей.',b)
 for d in BOOKS:
  b=crumbs('../../',d['title'])+'<div class="book-modules-main"><header class="sy-hero"><p class="eyebrow">Модуль чтения · 8 занятий</p><h1>'+E(d['title'])+'</h1><p class="sy-subtitle">'+E(d['subtitle'])+'</p><p class="lead">'+E(d['lead'])+'</p><div class="sy-actions"><a class="button" href="'+d['lessons'][0]['slug']+'/">Начать первое занятие →</a><a class="button secondary" href="#program">Посмотреть маршрут</a><a href="notebook/">Тетрадь модуля</a></div>'+progress(d)+'</header><section class="sy-intro"><div><h2>Как устроено чтение</h2>'+p(d['scope'])+'<p>Ориентир — 20–35 минут на занятие, с возможностью возвращаться. Русского пояснения достаточно для первого прохода; по ссылке можно найти указанный раздел источника. Каждое занятие заканчивается двумя вопросами для самопроверки. Отметку о продвижении ставите Вы.</p></div><div class="sy-principles">'+''.join('<p><strong>'+E(a)+'</strong><br>'+E(t)+'</p>' for a,t in d['methods'])+'</div></section><section id="program" class="section"><h2>Восемь встреч с книгой</h2><div class="sy-cards">'
  for l in d['lessons']:b+=f'<article class="sy-card"><span class="sy-number">{l["id"]:02d}</span><h3><a href="{l["slug"]}/">{E(l["title"])}</a></h3><p>{E(l["aim"][0].upper()+l["aim"][1:])}</p><small>'+E('; '.join(r['label'] for r in l['refs']))+f'</small><small data-book-mark="{l["id"]}">Можно начать</small></article>'
  b+='</div></section>'+sources(d)+'<p class="book-crosslinks"><a href="/course/book-studies/">← Все модули по книгам</a></p></div>'+payload(d)
  page(base(d),d['title']+' — '+d['subtitle'],d['lead'],b)
  for l in d['lessons']:
   side='<aside class="sy-side"><details class="toc" open><summary>Занятия модуля</summary><ol>'+''.join(f'<li><a href="{link(d,x)}" {"aria-current=page" if x["id"]==l["id"] else ""}><span>{x["id"]:02d}</span> {E(x["title"])}</a></li>' for x in d['lessons'])+'</ol><a href="../notebook/">Мои записи →</a></details></aside>'
   b=crumbs('../../../',d['title']+' · '+str(l['id']))+'<div class="book-modules-main"><p class="sy-back"><a href="../">← Весь модуль</a></p><div class="sy-shell">'+side+f'<article class="sy-lesson" data-book-lesson="{l["id"]}"><header><p class="eyebrow">{E(d["title"])} · Занятие {l["id"]} из 8</p><h1>{E(l["title"])}</h1><p class="lead">После занятия Вы сможете {E(l["aim"])}</p><p class="fine">20–35 минут; можно читать частями · <a href="#sources">Источники</a></p>'+progress(d)+'</header><nav class="sy-lesson-steps" aria-label="Шаги занятия"><a href="#before">Первый вопрос</a><a href="#reading">Чтение</a><a href="#practice">Исследование</a><a href="#check">Самопроверка</a><a href="#reflection">Моя запись</a></nav>'
   b+='<section class="sy-before" id="before"><p class="eyebrow">Перед объяснением</p><h2>Сначала Ваша мысль</h2>'+field('before',l['question'])+'</section><section id="reading"><p class="book-reading-label">Читаем выбранное место · учебный пересказ</p>'+p(l['passage'])+'<p class="book-source-link">'+''.join('<a href="'+r['url']+'" target="_blank" rel="noopener noreferrer">'+E(r['label'])+' →</a><br>' for r in l['refs'])+'</p></section>'
   b+=''.join('<section class="sy-reading"><h2>'+E(x['title'])+'</h2>'+''.join(p(t) for t in x['text'])+'</section>' for x in l['sections'])+lab(d,l)
   if d['book']=='pardes-rimmonim':b+='<p class="book-crosslinks"><a class="button secondary" href="/course/reading-workshop/?source=p'+str(l['id'])+'">Развить эту мысль в мастерской комментария →</a></p>'
   b+='<section id="check" class="sy-quiz"><p class="eyebrow">Самопроверка</p><h2>Могу ли я объяснить?</h2><p>Вопросы проверяют понимание прочитанного. Можно пробовать несколько раз.</p>'
   for i,q in enumerate(l['quiz']):b+=f'<fieldset disabled data-book-enhanced><legend>{i+1}. {E(q["q"])}</legend>'+''.join(f'<label class="sy-option"><input type="radio" name="book-q-{i}" value="{j}" data-book-answer="{i}"> <span>{E(o)}</span></label>' for j,o in enumerate(q['options']))+f'<p role="status" data-book-q-feedback="{i}"></p></fieldset>'
   b+=button('Проверить ответы','data-book-quiz-check')+'<p class="sy-feedback" data-book-quiz-result role="status"></p>'+solution(' '.join(str(i+1)+'. '+q['options'][q['answer']]+'. '+q['why'] for i,q in enumerate(l['quiz'])),'Пояснения к вопросам')+'</section><section id="reflection" class="sy-reflection"><p class="eyebrow">После чтения</p><h2>Своими словами</h2>'+field('note',l['reflection'],7)+solution(l['sample'],'Пример хода мысли')+'<label class="sy-check"><input type="checkbox" data-book-done disabled data-book-enhanced> Отмечаю занятие как пройденное</label><p class="fine">Записи сохраняются в этом браузере на этом устройстве и не отправляются автору курса. <a href="../notebook/">Открыть тетрадь и скачать копию →</a></p></section><aside class="sy-return"><h2>Вернуться позже</h2>'+p(l['returnTask'])+'</aside><section class="book-glossary"><h2>Слова этого занятия</h2><dl>'+''.join('<dt>'+E(a)+'</dt><dd>'+E(t)+'</dd>' for a,t in l['terms'])+'</dl></section>'+sources(d,l)+'<nav class="sy-next" aria-label="Соседние занятия">'
   prev=d['lessons'][l['id']-2] if l['id']>1 else None;nxt=d['lessons'][l['id']] if l['id']<len(d['lessons']) else None
   b+=(f'<a href="{link(d,prev)}">← {E(prev["title"])}</a>' if prev else '<a href="../">← Начало модуля</a>')+(f'<a href="{link(d,nxt)}">{E(nxt["title"])} →</a>' if nxt else '<a href="../notebook/">Моя тетрадь →</a>')+'</nav></article></div></div>'+payload(d,l)
   page(link(d,l),l['title']+' — '+d['title'],l['aim'][0].upper()+l['aim'][1:],b)
  b=crumbs('../../../','Тетрадь · '+d['title'])+'<div class="book-modules-main"><header class="sy-hero"><p class="eyebrow">Личные записи</p><h1>Моя тетрадь<br><em>'+E(d['title'])+'</em></h1><p class="lead">Первое предположение, работа с текстом и мысль после чтения.</p>'+progress(d)+'<p>Тетрадь хранит записи 8 занятий этой книги. Они остаются в браузере на этом устройстве. Перед очисткой браузера или переносом на другое устройство скачайте копию.</p><div class="sy-actions">'+button('Скачать тетрадь модуля','data-book-export')+button('Скачать записи текстом','data-book-export-text',True)+'</div><details class="sy-solution"><summary>Перенести записи модуля</summary><p>Выберите JSON-файл, сохранённый тетрадью этой книги. Прежние записи сохранятся; отличающиеся тексты добавятся с пометкой.</p><label for="book-import">Файл тетради «'+E(d['title'])+'»</label><input type="file" id="book-import" accept="application/json,.json"><p data-book-import-status role="status"></p></details><p><a href="../">К занятиям модуля →</a> · <a href="/course/book-studies/">Все книги →</a></p></header><section data-book-notebook><noscript><p>Для просмотра, редактирования и переноса записей включите JavaScript.</p></noscript></section></div>'+payload(d)
  page(base(d)+'notebook/','Моя тетрадь — '+d['title'],'Личные записи 8 занятий: первое предположение, черновик, итоговая мысль и перенос тетради.',b,noindex=True)
