"""Six source-attributed lessons and a complete 16-court atlas."""
from pathlib import Path
from html import escape as E
import json

ROOT=Path(__file__).resolve().parents[1]
BASE='/course/court-relations/'
D=json.loads((ROOT/'content/court-relations.json').read_text())
METHOD=json.loads((ROOT/'content/tarot-pairs.json').read_text())
RANKS=['14','13','12','11'];SUITS=['w','c','s','p']
ALL_CARDS={c['id']:c for c in json.loads((ROOT/'content/tarot.json').read_text())['cards']}
CARDS=[]
for suit in SUITS:
    for rank in RANKS:
        id=suit+rank;c=ALL_CARDS[id];r=METHOD['courts'][rank];m=METHOD['suits'][suit]
        CARDS.append(dict(c,**D['profiles'][id],rank=rank,suitId=suit,rankElement=r['element'],suitElement=m['element'],suitName=m['name'],world=m['world'],letter=r['letter'],letterName=D['ranks'][rank]['letterName']))
BY_ID={c['id']:c for c in CARDS}
LABELS={'question':'Вопрос исследования','before':'Первое чтение или чтение без скрытой карты','after':'Что меняется после возвращения, перестановки или переворота','reading':'Моё чтение отношений и целого','basis':'Источник / соответствие / моя гипотеза','alternative':'Другая гипотеза и недостающие сведения','step':'Какое действие или наблюдение поможет уточнить'}
def p(t):return '<p>'+E(t)+'</p>'
def payload(l=None):
    data={'title':D['title'],'lessons':[{k:x[k] for k in ['id','slug','title','default']} for x in D['lessons']],'current':l['id'] if l else 0,'quiz':l['quiz'] if l else []}
    return '<script id="court-relations-data" type="application/json">'+json.dumps(data,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')+'</script>'
def progress():return '<div class="sg-progress"><progress value="0" max="6" aria-label="Прогресс модуля" data-cr-progress></progress><span data-cr-count>Отмечено 0 из 6 занятий</span></div>'
def sources(l=None):
    out='<section id="sources" class="sg-section sg-sources"><h2>Источники и метод</h2>'
    for key in l['refs'] if l else D['sources']:
        x=D['sources'][key];out+='<p><a href="'+E(x['url'],quote=True)+'" target="_blank" rel="noopener noreferrer">'+E(x['title'])+'</a><br>'+E(x['detail'])+'</p>'
    return out+p('Еврейские источники, герметическая таблица и практическая интерпретация обозначены отдельно. В курсе применяется оговорённая адаптация рангов для изображений Уэйта–Смит. Шестнадцать вопросов, возможные искажения, примеры и упражнения написаны для курса. Изображения и их источники доступны по ссылкам у карт. Подсчёт признаков не оценивает истинность толкования.')+'</section>'
def controls():return '<div class="sg-actions"><button type="button" class="button" id="cr-export" disabled data-cr-enable>Скачать тетрадь JSON</button><button type="button" class="button secondary" id="cr-export-text" disabled data-cr-enable>Скачать записи TXT</button></div><label class="sg-field">Перенести тетрадь этого модуля<input type="file" id="cr-import" accept=".json,application/json" disabled data-cr-enable></label><p id="cr-import-status" role="status"></p>'
def laboratory(l):
    out='<section id="laboratory" class="sg-section"><p class="eyebrow">Лаборатория отношений</p><h2>Ранг, область и место в целом</h2><p>Выберите одну, две или четыре разные придворные карты. Для пары доступны оба порядка, для четвёрки — все 24. Вопросы позиций остаются на месте, ориентация перемещается вместе с картой.</p><div id="cr-lab" hidden><div class="sg-controls"><label>Схема исследования<select id="cr-size"><option value="court1">Одна фигура</option><option value="court2">Диалог двух функций</option><option value="court4">Четыре функции</option><option value="pairs">Две пары</option></select></label><label id="cr-partition-control">Разбиение на пары<select id="cr-partition"><option value="0">АБ / ВГ</option><option value="1">АВ / БГ</option><option value="2">АГ / БВ</option></select></label></div><div class="sg-actions"><button type="button" class="button secondary" id="cr-reverse">Обратный порядок</button><button type="button" class="button secondary" id="cr-preset-suit">Четыре ранга Жезлов</button><button type="button" class="button secondary" id="cr-preset-rank">Четыре Королевы</button><button type="button" class="button secondary" id="cr-preset-whole">Четыре разных роли</button></div><p class="fine">Переключение схемы, набора, порядка или ориентации открывает отдельный вариант. Предыдущие записи доступны ниже в «Моих других вариантах». Первое и повторное чтение одного опыта удобно записать в двух полях той же версии.</p><div class="cr-controls-row"><label>Карта для опыта отсутствия<select id="cr-focus"></select></label><button type="button" class="button secondary" id="cr-omit" aria-pressed="false">Временно скрыть карту</button></div><p class="fine">Скрытие меняет видимость карты и подсказки к связям. Оно сохраняет набор и текст Вашего варианта.</p><div id="cr-cards" class="cr-cards"></div><section class="cr-diagnosis" aria-live="polite"><h3 id="cr-structure-title"></h3><p id="cr-structure-text"></p><div id="cr-groups"></div><details><summary>Попарные сопоставления видимых карт</summary><div id="cr-joins"></div></details></section><details class="sg-disclosure"><summary>Все порядки выбранных карт</summary><p id="cr-order-count"></p><div id="cr-orders"></div></details><div id="cr-constructor-links" class="sg-actions"></div>'
    for key,label in LABELS.items():out+='<label class="sg-field">'+E(label)+f'<textarea data-cr-field="{key}" rows="'+('2' if key=='question' else '4')+'" maxlength="12000"></textarea></label>'
    out+='<div class="sg-actions"><button type="button" class="button" id="cr-snapshot">Зафиксировать разбор</button><button type="button" class="button secondary" id="cr-review">Проверить полноту</button></div><p id="cr-snapshot-status" role="status"></p><p id="cr-review-status" role="status"></p><details class="sg-disclosure"><summary>Мои другие варианты занятия</summary><div id="cr-variants"></div></details></div><noscript><p>Для выбора карт и тетради нужен JavaScript. Объяснения, исходные карты, примеры, ответы и полный атлас доступны без него.</p></noscript><p id="cr-save-status" role="status">Записи остаются в памяти этого браузера.</p></section>'
    return out
def example(l):
    e=l['example'];out='<details class="sg-disclosure"><summary>Разобранный пример: '+E(e['title'])+'</summary><div class="sg-static-cards">'
    for id in l['default']['ids']:
        c=BY_ID[id];out+='<figure><a href="'+E(c['imageSource'],quote=True)+'" target="_blank" rel="noopener noreferrer"><img loading="lazy" src="'+E(c['image'],quote=True)+'" width="85" height="147" alt="'+E(c['name'],quote=True)+'"></a><figcaption>'+E(c['name'])+'</figcaption></figure>'
    out+='</div>'
    for key,label in [('text','Возможное чтение'),('basis','Основание'),('alternative','Альтернатива')]:out+='<h3>'+label+'</h3>'+p(e[key])
    return out+'</details>'
def atlas():
    out='<section id="correspondences" class="sg-section"><h2>Четыре буквы: источник и адаптация</h2><p>Таблица сефиротических соответствий — по Мазерсу, § 67; различие функций букв можно прочитать в Игерет ха-тшува 4:9–19. Столбец Book T учитывает общий раздел и отдельные названия карт. Последний столбец задаёт соглашение нашего курса для Уэйта–Смит.</p><div class="cr-table-wrap" tabindex="0" role="region" aria-label="Сопоставление названий придворных"><table class="cr-table"><caption>Буква, сефиротическая связь и названия ранга</caption><thead><tr><th scope="col">Буква и место</th><th scope="col">Связь с сефирот</th><th scope="col">Book T</th><th scope="col">В курсе · Уэйт–Смит</th></tr></thead><tbody>'
    for rank in RANKS:
        x=D['ranks'][rank];r=METHOD['courts'][rank]
        out+='<tr><th scope="row"><span lang="he">'+r['letter']+'</span> '+E(x['letterName'])+'<small>'+E(x['place'])+'</small></th><td>'+E(x['sefirah'])+'</td><td>'+E(x['bookT'])+'</td><td>'+E(r['name']+' · '+r['element'])+'<small>'+E(x['function'])+'</small></td></tr>'
    out+='</tbody></table></div><p class="cr-reference">В первой и последней хе повторяется одна буква в разных местах. Сефиротическая связь буквы не превращает любую придворную карту в отдельную числовую сефиру. Придворные роли также не устанавливают пол, возраст или характер человека.</p></section>'
    out+='<section id="atlas" class="sg-section"><h2>Матрица 4 × 4 и атлас 16 карт</h2><p>Первая стихия формулы относится к рангу, вторая — к масти. Нажмите название в таблице, чтобы перейти к вопросу и подробной опоре ниже.</p><div class="cr-table-wrap" tabindex="0" role="region" aria-label="Матрица рангов и мастей"><table class="cr-table"><caption>Способ участия внутри области масти</caption><thead><tr><th scope="col">Ранг / способ</th>'
    for suit in SUITS:
        m=METHOD['suits'][suit];out+='<th scope="col">'+E(m['name'])+'<small>'+E(m['element']+' · '+m['world'])+'</small></th>'
    out+='</tr></thead><tbody>'
    for rank in RANKS:
        r=METHOD['courts'][rank];out+='<tr><th scope="row">'+E(r['name'])+'<small>'+E(r['element']+' · '+D['ranks'][rank]['letterName'])+'</small></th>'
        for suit in SUITS:
            c=BY_ID[suit+rank];out+='<td><a data-cr-jump="'+c['id']+'" href="#court-'+c['id']+'">'+E(c['name'])+'</a><small>'+E(c['formula'])+'</small></td>'
        out+='</tr>'
    out+='</tbody></table></div><div class="sg-controls"><label>Ранг<select id="cr-rank-filter" disabled data-cr-enable><option value="all">Все ранги</option>'+''.join('<option value="'+r+'">'+E(METHOD['courts'][r]['name'])+'</option>' for r in RANKS)+'</select></label><label>Масть<select id="cr-suit-filter" disabled data-cr-enable><option value="all">Все масти</option>'+''.join('<option value="'+s+'">'+E(METHOD['suits'][s]['name'])+'</option>' for s in SUITS)+'</select></label><label>Найти карту или тему<input type="search" id="cr-search" disabled data-cr-enable></label></div><p id="cr-atlas-count" role="status">Показано 16 из 16 карт</p><p class="fine">Вопросы, искажения и условия связи ниже — авторские учебные опоры.</p><div class="cr-atlas">'
    for c in CARDS:
        search=' '.join(c[k] for k in ['name','formula','letterName','world','title','question']).lower()
        out+='<article id="court-'+c['id']+'" data-cr-entry data-rank="'+c['rank']+'" data-suit="'+c['suitId']+'" data-search="'+E(search,quote=True)+'"><h3>'+E(c['name'])+'</h3>'+p(c['formula']+' · '+c['letterName']+' · '+c['world'])+'<details><summary>'+E(c['title'])+'</summary>'+p(c['question'])+'<p><strong>Возможное искажение.</strong> '+E(c['risk'])+'</p><p><strong>Условие связи.</strong> '+E(c['relation'])+'</p></details><p><a href="sixteen-fields/?a='+c['id']+'#laboratory">Исследовать эту карту →</a></p></article>'
    return out+'</div></section>'
def build(page,crumbs):
    assert len(CARDS)==16 and len({c['id'] for c in CARDS})==16 and len(D['lessons'])==6
    assert set(D['profiles'])==set(BY_ID)
    (ROOT/'assets/course/court-relations-atlas.js').write_text('window.CourtRelationsAtlas = '+json.dumps({'cards':CARDS},ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')+';\n')
    b=crumbs('../../','Придворные и отношения')+'<div class="sg-module cr-module"><header class="sg-hero"><p class="eyebrow">Продолжение курса · 6 занятий · 12 вопросов</p><h1>'+E(D['title'])+'</h1><p class="lead">'+E(D['lead'])+'</p><div class="sg-actions"><a class="button" href="name-and-roles/">Начать с четырёх букв →</a><a class="button secondary" href="#atlas">Все 16 карт</a><a href="notebook/">Моя тетрадь</a></div>'+progress()+'</header><section class="sg-section sg-intro"><div><h2>После путей и Старших арканов</h2><p>В <a href="../pathways/">предыдущем модуле</a> мы читали отношения между сефирот. Теперь обращаемся к придворным: ранг задаёт способ участия, масть — область, а позиция — вопрос к карте.</p><p>Каббалистическая опора — различие функций в едином Имени. Герметическая таблица и наши жизненные примеры рассмотрены отдельными шагами.</p></div><div><h2>Как заниматься</h2><p>На занятие — 25–40 минут. Прочитайте отрывок, проверьте соответствия и сформулируйте собственное объяснение. Затем сравните порядок, разбиение или опыт отсутствия карты.</p><p>Лаборатория допускает все 120 пар и 1 820 четвёрок из 16 разных придворных без повторов: 240 и 43 680 порядков соответственно. Разборы строятся по общей методологии; это не тысячи заранее написанных толкований.</p></div></section><section id="program" class="sg-section"><h2>Шесть занятий</h2><div class="sg-program">'
    for l in D['lessons']:b+=f'<article><span class="sg-number">{l["id"]:02d}</span><h3><a href="{l["slug"]}/">'+E(l['title'])+'</a></h3>'+p(l['aim'])+f'<span class="fine" data-cr-mark="{l["id"]}">Можно начать</span></article>'
    b+='</div></section>'+atlas()+sources()+'</div>'+payload();page(BASE,D['title'],D['lead'],b)
    for l in D['lessons']:
        assert len(l['quiz'])==2 and l['default']['ids'] and set(l['default']['ids'])<=set(BY_ID)
        b=crumbs('../../../','Придворные · '+str(l['id']))+'<div class="sg-module cr-module"><p><a href="../">← Весь модуль и атлас</a> · <a href="../notebook/">Моя тетрадь</a></p><header class="sg-lesson-hero"><p class="eyebrow">Занятие '+str(l['id'])+' из 6</p><h1>'+E(l['title'])+'</h1><p class="lead">'+E(l['aim'])+'</p>'+progress()+'</header><nav class="sg-lesson-nav" aria-label="Разделы занятия"><a href="#reading">Объяснение</a><a href="#task">Задание</a><a href="#laboratory">Лаборатория</a><a href="#check">Самопроверка</a><a href="#sources">Источники</a></nav><section id="reading" class="sg-reading"><h2>'+E(l['source']['title'])+'</h2>'+p(l['source']['text'])+'<p><strong>Вопрос к источнику.</strong> '+E(l['source']['question'])+'</p>'
        for s in l['sections']:b+='<section><h2>'+E(s['title'])+'</h2>'+''.join(p(t) for t in s['text'])+'</section>'
        b+='<p><a href="../#correspondences">Таблица букв и названий</a> · <a href="../#atlas">Матрица всех 16 карт</a></p></section><section id="task" class="sg-section"><h2>Попробуйте сами</h2><ol>'+''.join('<li>'+E(t)+'</li>' for t in l['task'])+'</ol>'+p('Исходные карты: '+' → '.join(BY_ID[id]['name'] for id in l['default']['ids']))+example(l)+'</section>'+laboratory(l)
        b+='<section id="check" class="sg-section sg-quiz"><h2>Могу ли я объяснить?</h2>'
        for i,q in enumerate(l['quiz']):b+=f'<fieldset disabled data-cr-enable><legend>{i+1}. '+E(q['q'])+'</legend>'+''.join(f'<label><input type="radio" name="cr-q-{i}" value="{j}" data-cr-answer="{i}"> '+E(o)+'</label>' for j,o in enumerate(q['options']))+f'<p id="cr-feedback-{i}" role="status"></p></fieldset>'
        b+='<button type="button" class="button" id="cr-check" disabled data-cr-enable>Проверить ответы</button><p id="cr-check-status" role="status"></p><details class="sg-disclosure"><summary>Ответы с объяснениями</summary>'+''.join('<p><strong>'+str(i+1)+'. '+E(q['options'][q['answer']])+'.</strong> '+E(q['why'])+'</p>' for i,q in enumerate(l['quiz']))+'</details></section><section class="sg-section"><label class="sg-complete"><input type="checkbox" id="cr-completed" disabled data-cr-enable> Отмечаю занятие как пройденное</label><details class="sg-disclosure"><summary>Скачать или перенести записи модуля</summary>'+controls()+'</details></section>'+sources(l)
        prev=D['lessons'][l['id']-2] if l['id']>1 else None;nxt=D['lessons'][l['id']] if l['id']<6 else None
        b+='<nav class="sg-next" aria-label="Соседние занятия">'+('<a href="../'+prev['slug']+'/">← '+E(prev['title'])+'</a>' if prev else '<a href="../">← Программа</a>')+('<a href="../'+nxt['slug']+'/">'+E(nxt['title'])+' →</a>' if nxt else '<a href="../notebook/">Тетрадь и наблюдения →</a>')+'</nav></div>'+payload(l)
        page(BASE+l['slug']+'/',l['title']+' — придворные и отношения',l['aim'],b)
    b=crumbs('../../../','Тетрадь придворных')+'<div class="sg-module cr-module"><header class="sg-hero"><p class="eyebrow">Отдельная тетрадь модуля</p><h1>Мои исследования придворных</h1><p class="lead">Роли, отношения, порядок карт, основания и наблюдения.</p>'+progress()+'<p>Записи остаются в этом браузере на этом устройстве. Автор курса их не получает. Скачайте JSON для переноса и резервной копии; TXT подходит для чтения.</p>'+controls()+'<p id="cr-save-status" role="status"></p><p><a href="../">К программе и атласу →</a></p></header><section class="sg-section"><h2>Мои варианты</h2><label class="sg-field">Найти по карте, вопросу или тексту<input type="search" id="cr-note-search" disabled data-cr-enable></label><div id="cr-notes"></div><button type="button" class="button secondary" id="cr-more" hidden>Показать ещё</button></section><section class="sg-section"><h2>Сохранённые разборы и возвращения</h2><p>Новые факты добавляются отдельной записью. Исходный снимок остаётся прежним.</p><div id="cr-snapshots"></div><button type="button" class="button secondary" id="cr-snap-more" hidden>Показать ещё</button></section><noscript><p>Для личных записей и переноса тетради включите JavaScript.</p></noscript></div>'+payload();page(BASE+'notebook/','Тетрадь — придворные и отношения','Личная тетрадь модуля о придворных и отношениях.',b,noindex=True)
