"""Hecate learning line: authored lessons, static reading and progressive practice."""
from pathlib import Path
from html import escape as E
import json
ROOT=Path(__file__).resolve().parents[1]
D=json.loads((ROOT/'content/hekate.json').read_text())
BASE='/course/hekate/'
LS=D['lessons']
def p(t):return '<p>'+E(t)+'</p>'
def link(u,t):return '<a href="'+E(u,quote=True)+'">'+E(t)+'</a>'
def section(id,title,body):return '<section class="hk-section" id="'+id+'"><h2>'+E(title)+'</h2>'+body+'</section>'
def controls():return '<div class="hk-controls"><button type="button" class="button secondary" data-hk-export="json" disabled>Скачать JSON</button><button type="button" class="button secondary" data-hk-export="txt" disabled>Скачать TXT</button><label class="button secondary hk-import">Загрузить JSON<input type="file" accept=".json,application/json" data-hk-import disabled></label></div><p class="hk-status" data-hk-file-status role="status"></p>'
def field(name,label):return '<label class="hk-field">'+E(label)+'<textarea rows="4" data-hk-field="'+name+'" disabled></textarea></label>'
def progress():return '<div class="hk-progress"><progress max="28" value="0" aria-label="Пройденные занятия" data-hk-progress></progress><span data-hk-count>0 из 28 занятий</span></div>'
def payload(l=None):
 d={'lessons':[{k:x[k] for k in ('id','slug','title','recall','module')} for x in LS]}
 if l:d['lesson']={k:l[k] for k in ('id','slug','title','quiz')}
 return '<script type="application/json" id="hekate-data">'+json.dumps(d,ensure_ascii=False).replace('<','\\u003c')+'</script>'
def shell(body,l=None):
 nav='<nav class="hk-nav" aria-label="Учебная линия Гекаты">'+''.join(link(BASE+u,t) for u,t in [('','Программа'),('bridges/','Связи с каббалой и Таро'),('sources/','Источники'),('glossary/','Словарь'),('notebook/','Моя тетрадь')])+'</nav>'
 status='<p class="hk-storage" data-hk-storage role="status"></p><noscript><p class="hk-notice">Все тексты, задания и разборы доступны без JavaScript. Для сохранения записей и интерактивной проверки включите JavaScript; без него можно вести тетрадь отдельно и раскрывать ответы ниже.</p></noscript>'
 return '<div class="hk">'+nav+status+body+'</div>'+payload(l)
def refs(ids):
 return '<ol class="hk-sources">'+''.join('<li>'+link(D['sources'][k][1],D['sources'][k][0])+p(D['sources'][k][2])+'</li>' for k in ids)+'</ol>'
def bridges(l):return '<div class="hk-bridges">'+''.join('<div>'+link(u,t)+p(why)+'</div>' for u,t,why in l['bridges'])+'</div>'
def program(current=None):
 s='<div class="hk-program">'
 for i,(slug,title,aim) in enumerate(D['modules']):
  s+='<section data-hk-module><div class="hk-module-heading"><span>'+str(i+1).zfill(2)+'</span><div><h3>'+E(title)+'</h3>'+p(aim)+'</div></div><ol start="'+str(i*4+1)+'">'
  for l in LS[i*4:i*4+4]:
   s+='<li data-hk-item data-hk-search="'+E((l['title']+' '+l['aim']+' '+title).lower(),quote=True)+'"><a '+('aria-current="page" ' if current==l['id'] else '')+'href="'+BASE+l['slug']+'/"><span>'+str(l['id']).zfill(2)+'</span><span>'+E(l['title'])+'<small>'+E(l['aim'])+'</small></span><span data-hk-mark="'+str(l['id'])+'" class="hk-mark"></span></a></li>'
  s+='</ol></section>'
 return s+'</div>'
def quiz(l):
 s='<p>Выберите ответ и получите пояснение именно к своему варианту. Проверка не ограничивает доступ к следующим занятиям.</p>'
 for i,q in enumerate(l['quiz']):
  s+='<fieldset class="hk-question" data-hk-question="'+str(i)+'" disabled><legend>'+str(i+1)+'. '+E(q['q'])+'</legend>'+''.join('<label><input type="radio" name="hk-q-'+str(i)+'" value="'+str(j)+'"> '+E(v)+'</label>' for j,v in enumerate(q['options']))+'<p data-hk-feedback role="status"></p></fieldset>'
 s+='<button type="button" class="button" data-hk-check disabled>Проверить и разобрать</button><p data-hk-quiz-status role="status"></p><details class="hk-details"><summary>Открыть ответы и основания</summary>'+''.join('<p><strong>'+str(i+1)+'. '+E(q['options'][q['answer']])+'.</strong> '+E(q['feedback'][q['answer']])+'</p>' for i,q in enumerate(l['quiz']))+'</details>'
 return s
def rubric(final=False):
 rows=[('Источники','Нет места для проверки','Есть автор, но место или основание неполно','Указано место и показано, как оно поддерживает вывод'),('Различение','Смешаны эпохи или голоса','Различие названо, но теряется в выводе','Видно, где источник, авторское соответствие и собственное сравнение'),('Объяснение','Только список образов','Есть связь без ясного довода','Объяснено отношение деталей и назван предел вывода')]
 if final:rows.append(('Перенос','Новый случай не рассмотрен','Есть новый случай без изменения довода','Показано, что сохраняется и что меняется при замене материала'))
 return '<div class="hk-table-wrap"><table><caption>Самопроверка письменной работы. Сайт не оценивает свободный текст автоматически.</caption><thead><tr><th>Критерий</th><th>0 · Пока нет</th><th>1 · Частично</th><th>2 · Могу показать</th></tr></thead><tbody>'+''.join('<tr>'+''.join('<'+('th scope="row"' if j==0 else 'td')+'>'+E(x)+'</'+('th' if j==0 else 'td')+'>' for j,x in enumerate(row))+'</tr>' for row in rows)+'</tbody></table></div>'
def illustration():
 return '<svg class="hk-emblem" viewBox="0 0 380 330" role="img" aria-label="Учебная схема трёх путей: источники, каббала, Таро. В центре — их сопоставление"><circle cx="190" cy="160" r="126" fill="none" stroke="currentColor" opacity=".25"/><path d="M190 160V28M190 160L74 265M190 160L306 265" fill="none" stroke="currentColor" stroke-width="1.5"/><circle cx="190" cy="160" r="42" fill="#173541" stroke="currentColor"/><text x="190" y="165" text-anchor="middle">Геката</text><text x="190" y="18" text-anchor="middle">источники</text><text x="66" y="295" text-anchor="middle">каббала</text><text x="310" y="295" text-anchor="middle">Таро</text></svg>'
def visual(l):
 if l['id'] in (21,22,24):
  card_id={21:'18',22:'2',24:'9'}[l['id']]
  card=next(c for c in json.loads((ROOT/'content/tarot.json').read_text())['cards'] if c['id']==card_id)
  figure='<figure class="hk-card-figure"><img loading="lazy" src="'+E(card['image'],quote=True)+'" alt="'+E(card['scene'],quote=True)+'"><figcaption><strong>'+E(card['name'])+' · Уэйт—Смит</strong><br>'+E(card['scene'])+'<br>'+link(card['imageSource'],'Изображение Памелы Колман Смит · источник')+'</figcaption></figure>'
  if l['id']!=22:return figure
 else:figure=''
 if l['id']==17:
  return '<figure class="hk-diagram"><div class="hk-table-wrap"><table><caption>Liber 777 · одна строка, разные типы материала</caption><thead><tr><th>Шкала</th><th>Буква</th><th>XXXIV · Греческие боги</th><th>XIV · Таро</th></tr></thead><tbody><tr><td>13</td><td>Гимел</td><td>Артемида, Геката</td><td>II · Верховная Жрица</td></tr></tbody></table></div><figcaption>Учебная выписка из указанной системы. 13 — номер строки, II — номер карты. '+link(D['sources']['777'][1],'Сверить таблицы')+'.</figcaption></figure>'
 if l['id'] in (3,9):return '<figure class="hk-diagram"><ol class="hk-sequence"><li>Услышать<small>Граница знания</small></li><li>Искать вместе<small>Действие и помощь</small></li><li>Сопровождать<small>Продолжение связи</small></li></ol><figcaption>Наша схема выбранных эпизодов гимна к Деметре; не древняя таблица ступеней.</figcaption></figure>'
 if l['id']==22:return figure+'<figure class="hk-diagram"><ol class="hk-sequence"><li>Геката<small>Liber 777 · строка 13</small></li><li>Жрица<small>Два авторских прочтения</small></li><li>Шехина<small>Комментарий Уэйта</small></li></ol><figcaption>Связи принадлежат разным текстам. Цепочка показывает историю интерпретаций, а не тождество религиозных понятий.</figcaption></figure>'
 return ''
def lesson(page,crumbs,l):
 i=l['id'];mod=D['modules'][l['module']]
 b=crumbs('../../../','Геката · '+str(i))+'<header class="hk-lesson-header"><p class="eyebrow">'+E(mod[1])+' · занятие '+str(i)+' / 28</p><h1>'+E(l['title'])+'</h1><p class="lead">'+E(l['aim'])+'</p><p class="hk-meta">Ориентир: '+('60–90 минут для итоговой работы' if i==28 else '25–40 минут с письменным заданием')+' · можно остановиться и вернуться</p>'+progress()+'</header>'
 b+='<div class="hk-layout"><aside class="hk-outline"><p class="eyebrow">В этом занятии</p><nav aria-label="Шаги занятия">'+''.join(link('#'+x,t) for x,t in [('before','01 · Первый ответ'),('reading','02 · Материал'),('explanation','03 · Разбор'),('practice','04 · Ваша работа'),('check','05 · Самопроверка'),('return','06 · Возвращение')])+'</nav><details class="hk-details"><summary>Все 28 занятий</summary>'+program(i)+'</details><p>'+link(BASE+'notebook/','Открыть тетрадь →')+'</p></aside><article class="hk-reading">'
 b+=section('before','До чтения',p(l['opening'])+field('before','Мой первый ответ — можно коротко и с сомнениями')+'<label class="hk-field">Насколько уверен(а) в первом ответе?<select data-hk-field="confidence" disabled><option value="">Пока не выбираю</option><option value="low">Нужно разобраться</option><option value="medium">Есть предположение</option><option value="high">Могу обосновать</option></select></label>')
 b+=section('reading','Что читаем',p(l['reading'])+'<p class="hk-fine">Материал и объяснения на странице — авторский учебный пересказ, не цитата из опубликованного русского перевода. Для более подробного чтения откройте источники.</p>'+refs(l['refs']))
 b+='<div id="explanation">'+''.join(section('explanation-'+str(n+1),s['title'],p(s['text'])) for n,s in enumerate(l['sections']))+visual(l)+'</div>'
 b+=section('practice','Проверим на собственной работе',p(l['task'])+('<details class="hk-details" open><summary>Разобранный пример</summary>'+p(l['example'])+'</details>' if i<=4 else '<details class="hk-details"><summary>'+('Сначала попробуйте; затем откройте пример' if i>=17 else 'Открыть пример для сравнения')+'</summary>'+p(l['example'])+'</details>')+'<details class="hk-details"><summary>Нужна опора?</summary>'+p(l['hint'])+'</details>'+field('draft','Мой разбор / черновик')+'<details class="hk-details"><summary>Критерии самостоятельной проверки</summary>'+rubric(i==28)+'</details>'+field('revision','Уточнённая версия: что я изменил(а) и почему')+'<h3>Новый случай</h3>'+p(l['transfer'])+field('transfer','Как я переношу способ чтения на новый материал'))
 b+=section('check','Могу ли я объяснить?',quiz(l))
 b+=section('connections','Продолжить по связанной линии',bridges(l))
 b+=section('return','Вернуться и вспомнить',p(l['recall'])+field('recall','Мой ответ по памяти и вопрос на потом')+'<p>Закройте объяснение и ответьте своими словами. После отметки «пройдено» эта тема появится в тетради для возвращения через 1, затем 3 и 7 дней после успешного воспоминания. Напоминания не отправляются: список доступен здесь на сайте.</p><label class="hk-complete"><input type="checkbox" data-hk-complete disabled> Я прошёл(ла) занятие и проверил(а) свой разбор</label><p class="hk-status" data-hk-save role="status"></p><details class="hk-details"><summary>Скачать или перенести все записи линии</summary><p>Записи сохраняются в этом браузере. JSON — резервная копия и перенос, TXT — текст для чтения. Автор курса записей не получает.</p>'+controls()+'</details>')
 prev=BASE+LS[i-2]['slug']+'/' if i>1 else BASE
 nxt=BASE+LS[i]['slug']+'/' if i<len(LS) else BASE+'notebook/'
 b+='<nav class="hk-next" aria-label="Соседние занятия">'+link(prev,'← '+(LS[i-2]['title'] if i>1 else 'Программа'))+link(nxt,(LS[i]['title'] if i<len(LS) else 'Моя итоговая работа')+' →')+'</nav></article></div>'
 page(BASE+l['slug']+'/',l['title']+' — Геката',l['aim'],shell(b,l))
def build(page,crumbs):
 assert len(LS)==28 and [x['id'] for x in LS]==list(range(1,29))
 b=crumbs('../../','Геката')+'<header class="hk-hero"><div><p class="eyebrow">Ритуальная магия · связи с каббалой и Таро</p><h1>Геката.<br><em>Свет на перепутье.</em></h1><p class="lead">От античного гимна к философии, от имени богини к Жрице в Таро. Большой маршрут, в котором можно читать, сравнивать, пробовать и возвращаться к своим открытиям.</p><p class="hk-meta">7 разделов · 28 занятий · 56 вопросов с разбором · бесплатно</p><div class="actions"><a class="button gold" data-hk-resume href="first-meeting/">Начать знакомство →</a><a href="#program">Посмотреть весь маршрут</a></div>'+progress()+'</div>'+illustration()+'</header>'
 b+=section('start','Выберите удобный вход','<div class="hk-entry"><div><span>01 / Сначала</span><h3>Знакомлюсь с Гекатой</h3><p>Начните с мифа и простых вопросов к источнику. Предварительные знания не нужны.</p>'+link(BASE+'first-meeting/','Первое занятие →')+'</div><div><span>02 / Через книги</span><h3>Изучаю каббалу</h3><p>Врата, передача жизни, Шехина и таблицы соответствий. Ссылки ведут к конкретным книжным занятиям.</p>'+link(BASE+'gates/','Сравнить образ врат →')+'</div><div><span>03 / Через карты</span><h3>Уже читаю Таро</h3><p>Начните с проверенной связи Гекаты и Жрицы, затем сравните две Луны.</p>'+link(BASE+'correspondences/','Разобрать Liber 777 →')+'</div></div>')
 b+=section('time','Ориентиры во времени','<ol class="hk-timeline"><li><strong>Архаическая Греция</strong>Гесиод и гимн к Деметре.<span>Почести, помощь, поиск и сопровождение.</span></li><li><strong>Классическая Греция</strong>Еврипид и Аристофан.<span>Трагедия, комедия, дом и общественная жизнь.</span></li><li><strong>Римская эпоха и поздняя античность</strong>Павсаний, Орфические гимны, Оракулы, Ямвлих.<span>Описание культов, обращение, космология и теургия.</span></li><li><strong>Конец XIII века</strong>Йосеф Гикатила, Шаарей Ора.<span>Самостоятельная еврейская линия для сравнения.</span></li><li><strong>XIX–XX века</strong>Уэсткотт, Liber 777, Уэйт, Кроули.<span>Издание античного наследия и западные системы соответствий.</span></li><li><strong>Современность</strong>Новые сообщества, колоды и личные прочтения.<span>Рецепция с собственными авторами и задачами.</span></li></ol><p class="hk-fine">Это ориентиры для движения по курсу, а не доказанная цепочка непрерывной передачи одного учения. Точные места чтения приведены в занятиях.</p>')
 b+=section('method','Не только прочитать — суметь объяснить','<ol class="hk-method"><li><strong>Сначала свой ответ.</strong> Коротко запишите, что думаете сейчас.</li><li><strong>Затем источник и пример.</strong> Посмотрите, на чём основано объяснение.</li><li><strong>Самостоятельная попытка.</strong> Подсказки постепенно уходят в раскрываемые разделы.</li><li><strong>Новый случай.</strong> Проверьте способ чтения на другой карте или тексте.</li><li><strong>Редакция и возвращение.</strong> Сравните две версии ответа и восстановите мысль по памяти.</li></ol><p>Можно проходить по четыре занятия в неделю — один раздел. Это ориентир для семи недель; все материалы открыты сразу. Основное содержание изложено по-русски, ссылки на оригиналы и переводы позволяют углубить чтение.</p>')
 b+=section('connections','Три линии встречаются в конкретных местах',bridge_table()+'<p>'+link(BASE+'bridges/','Открыть атлас связей и упражнение →')+'</p>')
 b+=section('program','Полная программа','<label class="hk-field">Найти занятие<input type="search" data-hk-search-input placeholder="Например, Жрица, врата, символ" disabled></label><p class="hk-status" data-hk-search-status role="status"></p>'+program())
 b+=section('review','Пять минут на возвращение','<p>Пройденные темы возвращаются с интервалами. Сначала ответьте по памяти, затем проверьте себя.</p><div data-hk-review></div>')
 b+=section('finish','Что останется после курса','<p>Ваш путеводитель по Гекате: исторический портрет, разбор символа, обоснованные связи с каббалой и Таро, список источников и вопросы для продолжения. Черновик и редакция сохраняются отдельно.</p><div class="actions">'+link(BASE+'final-project/','Посмотреть итоговую работу →')+link(BASE+'notebook/','Открыть мою тетрадь →')+'</div><p class="hk-fine">Это завершённый вводный маршрут по выбранным источникам. Он не заменяет полного изучения всех местных культов, археологии и современных школ. Исторические сведения, религиозные утверждения и наши учебные аналогии обозначены в тексте.</p>')
 page(BASE,D['title'],'28 занятий о Гекате: античные тексты, культ, теургия, связи с каббалой и Таро. Самопроверка, тетрадь и возвращение к изученному.',shell(b))
 for l in LS:lesson(page,crumbs,l)
 extras(page,crumbs)
def bridge_table():
 return '<div class="hk-table-wrap"><table><caption>Чем обоснована каждая связь</caption><thead><tr><th>Что сопоставляем</th><th>Основание</th><th>Где изучаем</th></tr></thead><tbody><tr><td>Геката и Верховная Жрица</td><td>Соответствие у Кроули: Liber 777, XXXIV и XIV, строка 13</td><td>'+link(BASE+'correspondences/','Урок 17')+'</td></tr><tr><td>Жрица и Шехина</td><td>Прямой комментарий Уэйта к карте II</td><td>'+link(BASE+'priestess/','Урок 22')+'</td></tr><tr><td>Ключи Гекаты и врата Малхут</td><td>Наше сравнение образов доступа в разных текстах</td><td>'+link(BASE+'gates/','Урок 18')+'</td></tr><tr><td>Животворящий источник и Йесод</td><td>Наше сравнение отношений передачи; без тождества понятий</td><td>'+link(BASE+'living-source/','Урок 14')+'</td></tr><tr><td>Геката, Луна и Отшельник</td><td>Наше сопоставление дороги, света и сопровождения</td><td>'+link(BASE+'hermit/','Урок 24')+'</td></tr></tbody></table></div>'
def extras(page,crumbs):
 b=crumbs('../../../','Источники Гекаты')+'<header class="hk-lesson-header"><p class="eyebrow">Библиотека линии</p><h1>Читать с опорой<br>на источник</h1><p class="lead">Места чтения указаны в уроках; здесь собраны все использованные тексты и ориентиры. Большинство внешних материалов — на английском, часть — на иврите. Для базового маршрута достаточно русских объяснений в занятиях.</p></header>'
 for id,title,ids in [('ancient','Античные тексты',['hesiod','demeter','cult','myth','hymn','iamblichus']),('editions','Редакции и исследования',['oracles','johnston','shwep']),('western','Западные оккультные прочтения',['777','waite-priestess','waite-moon','waite-hermit','thoth','mathers']),('jewish','Еврейские источники',['gate1','gate2']),('modern','Современное самоописание',['covenant'])]:b+=section(id,title,refs(ids))
 b+=section('reading-rules','Как пользоваться библиотекой','<p>Сначала найдите автора и место, затем различите оригинал, перевод и комментарий. Для Халдейских оракулов сохраняйте название редакции вместе с номером. Старые переводы доступны для чтения, но их исторические примечания требуют проверки. Полные современные книги и ритуальные тексты здесь не перепечатываются.</p><p>Для дальнейшего исследования: Sarah Iles Johnston, <em>Hekate Soteira</em> (1990); Ruth Majercik, <em>The Chaldean Oracles</em> (1989). Библиографические сведения приведены в открытых научных материалах SHWEP. Эти книги расширяют тему; покупка и доступ к ним для прохождения линии не требуются.</p>')
 page(BASE+'sources/','Источники — Геката','Библиотека античных, каббалистических и оккультных источников учебной линии Гекаты.',shell(b))
 terms=[('Атрибуция','Приписывание текста, предмета или соответствия определённому автору, времени или системе. Нужно указать основание.','first-meeting'),('Герметическая Каббала','Западные эзотерические системы, использующие каббалистический словарь вместе с другими традициями и соответствиями. Отличаются от еврейских каббалистических школ.','correspondences'),('Гимн','Поэтическое обращение к божеству: может называть, восхвалять и просить. Жанр не равен справочной статье.','hymn'),('Гимел','Третья буква еврейского алфавита. В рассмотренной герметической таблице связана со строкой 13 и Жрицей; это не универсальное правило всех еврейских текстов.','correspondences'),('Йесод','«Основание», девятая сефира. В выбранном чтении Гикатилы раскрывается через передачу жизни к Малхут.','living-source'),('Лиминальность','Связь с порогом, границей и переходом; уточняйте конкретное место или отношение.','thresholds'),('Малхут','«Царство», десятая сефира и первые врата восходящего маршрута Гикатилы.','gates'),('Мистерии','Посвятительные обряды с ограниченным доступом к некоторым действиям и знаниям. Само слово не даёт полного сценария.','sanctuaries'),('Рецепция','Восприятие и переосмысление более раннего наследия в новом контексте.','modern'),('Сефира','Одна из десяти сефирот; её объяснение зависит от каббалистического автора. Это не просто другое слово для греческого божества.','gates'),('Синкретизм','Соединение элементов разных религиозных традиций. Назвать соединение недостаточно: нужно показать, кто, когда и как его осуществляет.','priestess'),('Теургия','В изучаемом позднеантичном контексте — священное действие, направленное на связь с божественным. У Ямвлиха не сводится к одной мысли.','symbols-theurgy'),('Хтонический','Связанный с землёй и подземной сферой в конкретном контексте; не синоним нравственного зла.','first-meeting'),('Шехина','Термин божественного присутствия в еврейской традиции. Уэйт использует его в собственном оккультном объяснении Жрицы.','presence'),('Эпитет','Определение при имени, указывающее на роль, место, качество или отношение. Не обязательно имя отдельной личности.','epithets')]
 b=crumbs('../../../','Словарь Гекаты')+'<header class="hk-lesson-header"><h1>Слова, к которым<br>можно вернуться</h1><p class="lead">Короткий ориентир. Полное объяснение находится в связанном занятии.</p></header><dl class="hk-glossary">'+''.join('<div><dt>'+E(t)+'</dt><dd>'+E(d)+' '+link(BASE+slug+'/','К занятию →')+'</dd></div>' for t,d,slug in terms)+'</dl>'
 page(BASE+'glossary/','Словарь — Геката','Понятия учебной линии: теургия, эпитет, лиминальность, рецепция, сефирот и соответствия.',shell(b))
 b=crumbs('../../../','Атлас связей')+'<header class="hk-lesson-header"><h1>Геката, каббала<br>и Таро</h1><p class="lead">Связь становится понятной, когда видны её автор, основание и границы.</p></header>'+section('map','Карта переходов',bridge_table())
 b+=section('classify','Попробуйте различить основания','<p>Выберите тип связи для каждого утверждения. Здесь оценивается основание фразы, а не правильность Вашего личного духовного опыта.</p><div data-hk-classify></div><noscript><ol><li>«В Liber 777 Геката стоит в строке Жрицы» — соответствие конкретного автора.</li><li>«В гимне Геката слышит крик» — сообщение древнего источника.</li><li>«Для меня ключ — образ готовности учиться» — личная аналогия.</li><li>«Геката и Малхут всегда были одним божеством» — утверждение без достаточного основания в рассмотренных текстах.</li></ol></noscript>')
 b+=section('routes','Продолжить по своему вопросу','<div class="hk-entry"><div><h3>Каббала</h3><p>Врата → передача → присутствие → триады.</p>'+link(BASE+'gates/','Начать сравнение →')+'</div><div><h3>Таро</h3><p>Liber 777 → Жрица → две Луны → свой разбор.</p>'+link(BASE+'correspondences/','Проверить соответствие →')+'</div><div><h3>Ритуальная магия</h3><p>Гимн → символ → теургия → современная рецепция.</p>'+link(BASE+'hymn/','Читать обращение →')+'</div></div>')
 page(BASE+'bridges/','Связи Гекаты с каббалой и Таро','Проверенные авторские соответствия и учебные сопоставления с объяснением границ.',shell(b))
 b=crumbs('../../../','Тетрадь Гекаты')+'<header class="hk-lesson-header"><h1>Мои чтения<br>и открытия</h1><p class="lead">Первые ответы, черновики, уточнения и возвращения к изученному. Записи остаются в этом браузере; автор курса их не получает.</p>'+progress()+controls()+'</header>'+section('review','Вспомнить без подсказки','<p>Сначала попробуйте ответить, затем откройте своё занятие. «Вспомнил(а)» переносит тему на следующий интервал; «Повторить завтра» даёт ещё одну попытку.</p><div data-hk-review></div>')+section('notes','Мои записи','<label class="hk-field">Найти занятие или запись<input type="search" data-hk-notes-search disabled></label><div data-hk-notes></div>')
 page(BASE+'notebook/','Моя тетрадь — Геката','Личные записи и повторение материала учебной линии Гекаты.',shell(b),noindex=True)
 b=crumbs('../../','Ритуальная магия')+'<section class="hero-small"><p class="eyebrow">Третья линия проекта</p><h1>Европейская<br>ритуальная магия</h1><p class="lead">Читаем тексты, разбираем символы и следим, как античное наследие встречается с каббалой и Таро в конкретных авторских системах.</p></section><section class="section"><h2>Геката: большой учебный маршрут</h2><p>28 занятий от Гесиода и гимна к Деметре до теургии, Liber 777 и Жрицы. Источники, примеры, самостоятельные работы и тетрадь.</p><a class="button" href="/course/hekate/">Открыть линию Гекаты →</a></section><section class="section"><h2>Продолжить по книгам</h2><div class="actions">'+link('/course/levi-dogma-ritual/','Леви: учение и ритуал')+link('/course/mystical-qabalah/','Форчун: герметическая Каббала')+link('/course/book-of-thoth/','Кроули: Книга Тота')+'</div><p>Этот раздел растёт из конкретных источников. Античные, еврейские и поздние западные учения изучаются со своими именами и историей.</p></section>'
 page('/course/ritual-magic/','Европейская ритуальная магия','Третья линия курса: Геката, античные основы, теургия и западные оккультные системы.',b)
