"""Build three source-based reading tools, with private local notes."""
from pathlib import Path
from html import escape as E
import json
ROOT=Path(__file__).resolve().parents[1]
D=json.loads((ROOT/'content/study-tools.json').read_text())
FIELDS={'comment':{'literal':'Что сказано в выбранном месте?','terms':'Какие слова требуют пояснения?','meaning':'Как я понимаю ход мысли?','evidence':'На какие слова или отношения я опираюсь?','question':'Что ещё осталось непонятным?','analogy':'Моя аналогия и её граница'},'compare':{'shared':'В чём сходство?','difference':'В чём существенное различие?','evidence':'Какое место каждого текста подтверждает сравнение?','limit':'Какой вывод делать пока нельзя?'},'clinic':{'correction':'Моя исправленная формулировка','reason':'Почему я изменил(а) эту фразу?'}}
def button(t,attr='',secondary=False):return '<button type="button" class="button'+(' secondary' if secondary else '')+'" '+attr+'>'+E(t)+'</button>'
def field(k,t):return '<label class="st-field" for="st-'+k+'"><span>'+E(t)+'</span><textarea id="st-'+k+'" data-st-field="'+k+'" rows="3" maxlength="8000"></textarea></label>'
def nav():return '<nav class="st-nav" aria-label="Мастерские"><a href="/course/study-tools/">Все мастерские</a><a href="/course/reading-workshop/">Комментарий</a><a href="/course/compare-authors/">Сравнение</a><a href="/course/argument-clinic/">Поиск ошибки</a><a href="/course/study-tools/notebook/">Мои редакции</a></nav>'
def source(s):return '<article class="st-source"><h3>'+E(s['title'])+'</h3><p class="st-label">Учебный пересказ · слова курса</p><p>'+E(s['text'])+'</p><a href="'+E(s['url'],quote=True)+'" target="_blank" rel="noopener noreferrer">'+E(s['label'])+' →</a></article>'
def wrap(crumbs,title,lead,body,mode):
 data={k:[({a:x[a] for a in ['id','title','answer','why']} if k=='errors' and mode=='clinic' else {a:x[a] for a in ['id','title']}) for x in v] for k,v in D.items()};data.update(mode=mode,fieldLabels=FIELDS)
 return crumbs('../../' if mode!='notebook' else '../../../',title)+'<div class="st-main">'+nav()+'<header class="st-hero"><p class="eyebrow">Читаем · объясняем · проверяем основания</p><h1>'+E(title)+'</h1><p class="lead">'+E(lead)+'</p></header><p class="notice">Записи сохраняются в этом браузере на этом устройстве. Они не отправляются автору курса. <a href="/course/study-tools/notebook/">Скачать копию и посмотреть редакции →</a></p><p id="st-status" role="status" aria-live="polite"></p><noscript><p>Для упражнений и записи включите JavaScript. Источники и пояснения доступны ниже.</p></noscript>'+body+'</div><script type="application/json" id="study-tools-data">'+json.dumps(data,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')+'</script>'
def selector(items,label):return '<label class="st-select" for="st-select">'+E(label)+'<select id="st-select">'+''.join('<option value="'+x['id']+'">'+E(x['title'])+'</option>' for x in items)+'</select></label>'
def review(kind):return '<section class="st-panel"><h2>Моя работа</h2>'+''.join(field(k,v) for k,v in FIELDS[kind].items())+'<div class="st-actions">'+button('Сохранить редакцию','data-st-snapshot')+button('Проверить полноту записи','data-st-review',True)+'</div><p data-st-feedback role="status"></p><p class="fine">Проверка отмечает заполненные части. Смысл и качество толкования Вы оцениваете по основаниям, источнику и границам вывода.</p><details class="st-revisions"><summary>Первый вариант и сохранённые редакции</summary><div data-st-revisions></div></details></section>'
def build(page,crumbs):
 cards=[('01','Мастерская комментария','От первого предположения к объяснению: источник, основания, открытый вопрос и редакции.','reading-workshop'),('02','Сравнение авторов','Три пары текстов: что похоже, чем различается и где заканчивается сравнение.','compare-authors'),('03','Поиск ошибки','Восемь коротких разборов: найдите неверный переход и перепишите фразу.','argument-clinic')]
 body='<section class="st-grid">'+''.join('<article class="st-card"><span class="eyebrow">'+n+'</span><h2>'+t+'</h2><p>'+d+'</p><a class="button secondary" href="/course/'+u+'/">Открыть →</a></article>' for n,t,d,u in cards)+'</section><section class="st-panel"><h2>Один цикл работы</h2><ol><li>Прочитайте небольшой фрагмент и сначала запишите собственную мысль.</li><li>Сохраните редакцию, откройте образец и сравните основания.</li><li>Уточните объяснение. Сохраните новую редакцию: первый вариант останется.</li><li>Через несколько дней попробуйте объяснить без подсказки, затем сверьтесь с книгой.</li></ol><p>В образце показан один возможный ход мысли. Он помогает увидеть структуру ответа, но не заменяет самостоятельного чтения.</p><p><a href="/course/pardes-rimmonim/">Начать восемь занятий по «Пардес римоним» →</a> · <a href="/course/book-studies/">Выбрать другую книгу →</a></p></section>'
 page('/course/study-tools/','Мастерские чтения','Три инструмента для комментария, сравнения авторов и проверки аргументов.',wrap(crumbs,'Мастерские чтения','От узнавания знакомых слов — к объяснению, которое можно обосновать.',body,'hub'))
 body=selector(D['comments']+[{'id':'custom','title':'Мой фрагмент из другой книги'}],'Выберите место для комментария')
 for x in D['comments']:
  s=dict(x,title='Пардес римоним · '+x['title']);body+='<section data-st-item="'+x['id']+'">'+source(s)+'<details class="st-model"><summary>Показать образец хода мысли</summary><p>'+E(x['model'])+'</p><p>Сопоставьте основания, затем уточните свою запись ниже.</p></details></section>'
 body+='<section data-st-item="custom"><h2>Фрагмент, который Вы выбрали</h2>'+field('reference','Книга, автор, раздел и ссылка')+field('excerpt','Короткий фрагмент или Ваш пересказ с указанием, что это пересказ')+'<p>Для собственного текста готового образца нет. Используйте вопросы мастерской и вернитесь к источнику.</p></section>'+review('comment')
 page('/course/reading-workshop/','Мастерская комментария','Читаем источник, записываем основания и сохраняем редакции собственного комментария.',wrap(crumbs,'Мастерская комментария','Сначала попробуйте сами. Образец можно открыть после первой записи; перед его открытием непустой черновик сохраняется как редакция.',body,'comment'))
 body=selector(D['comparisons'],'Выберите два текста')
 for x in D['comparisons']:body+='<section data-st-item="'+x['id']+'"><h2>'+E(x['question'])+'</h2><div class="st-columns">'+source(x['left'])+source(x['right'])+'</div><details class="st-model"><summary>Показать пример сравнения</summary><p>'+E(x['model'])+'</p></details></section>'
 body+=review('compare')
 page('/course/compare-authors/','Сравнение авторов и книг','Три пары текстов: метафоры, задачи чтения и разные традиции Древа.',wrap(crumbs,'Сравнение авторов и книг','Положите рядом два небольших текста. Найдите общее отношение, существенное различие и предел сопоставления.',body,'compare'))
 body=selector(D['errors'],'Выберите рассуждение')
 for x in D['errors']:
  body+='<section class="st-panel" data-st-item="'+x['id']+'"><h2>'+E(x['title'])+'</h2><p class="st-label">Специально составленное ошибочное рассуждение</p><blockquote>'+E(x['claim'])+'</blockquote><details><summary>Подсказка</summary><p>'+E(x['hint'])+'</p></details><fieldset><legend>В чём ошибка?</legend>'+''.join('<label class="st-option"><input type="radio" name="'+x['id']+'" value="'+str(i)+'"> <span>'+E(t)+'</span></label>' for i,t in enumerate(x['options']))+'</fieldset>'+button('Проверить выбор','data-st-check="'+x['id']+'"')+'<p class="st-result" data-st-result="'+x['id']+'" role="status"></p><details class="st-model"><summary>Разбор и один вариант исправления</summary><p>'+E(x['why'])+'</p><p>'+E(x['fix'])+'</p></details><p><a href="'+E(x['url'],quote=True)+'" target="_blank" rel="noopener noreferrer">'+E(x['label'])+' →</a></p></section>'
 body+=review('clinic')
 page('/course/argument-clinic/','Найти ошибку в рассуждении','Восемь упражнений с подсказками, объяснениями и собственной исправленной формулировкой.',wrap(crumbs,'Найти ошибку в рассуждении','Здесь проверяется конкретный переход от текста к выводу. После выбора обязательно попробуйте переписать исходную фразу.',body,'clinic'))
 body='<section class="st-panel"><h2>Копия Вашей работы</h2><div class="st-actions">'+button('Скачать JSON для переноса','data-st-export')+button('Скачать записи текстом','data-st-text',True)+'</div><details><summary>Загрузить записи мастерских</summary><p>Выберите JSON, скачанный здесь. Отличающиеся тексты добавятся с пометкой; сохранённые редакции объединятся. При ошибке файл не меняет текущую тетрадь.</p><label for="st-import">Файл тетради мастерских</label><input type="file" id="st-import" accept="application/json,.json"></details><p>Копия включает записи всех трёх мастерских. Тетради книжных занятий скачиваются отдельно.</p><a href="/course/pardes-rimmonim/notebook/">Тетрадь занятий «Пардес римоним» →</a></section><section id="st-notebook"></section>'
 page('/course/study-tools/notebook/','Тетрадь мастерских','Ваши черновики, редакции комментариев, сравнений и исправлений.',wrap(crumbs,'Моя тетрадь мастерских','Первый вариант остаётся рядом с последующими: можно увидеть, как менялось объяснение.',body,'notebook'),noindex=True)
