"""Render the Sefer Yetzirah reading module from attributed editorial content."""
from pathlib import Path
from html import escape as E
import json, math
ROOT=Path(__file__).resolve().parents[1]
D=json.loads((ROOT/'content/yetzirah.json').read_text())
BASE='/course/yetzirah/'
def link(l):return BASE+l['slug']+'/'
def button(text,attrs='',secondary=False):return f'<button type="button" class="button {"secondary" if secondary else ""}" disabled data-sy-enhanced {attrs}>{E(text)}</button>'
def paras(texts):return ''.join('<p>'+E(t)+'</p>' for t in texts)
def payload(current=0):
 x={'current':current,'lessons':[{k:l[k] for k in ['id','slug','title','quiz','reflection']} for l in D['lessons']],'comparisons':D['comparisons'],'months':D['months']}
 return '<script id="sy-data" type="application/json">'+json.dumps(x,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')+'</script>'
def progress():return '<div class="sy-progress"><progress max="12" value="0" aria-label="Прогресс модуля" data-sy-bar></progress><span data-sy-progress>Пройдено 0 из 12 занятий</span></div>'
def match(items):
 s='<fieldset class="sy-match" disabled data-sy-enhanced><legend>Соберите соответствия</legend>'
 for i,(prompt,answer,opts) in enumerate(items):
  s+=f'<div class="sy-match-row"><label for="sy-match-{i}">{E(prompt)}</label><select id="sy-match-{i}" data-sy-answer="{E(answer,quote=True)}" aria-describedby="sy-result-{i}"><option value="">Выберите…</option>'+''.join(f'<option>{E(o)}</option>' for o in opts)+f'</select><small id="sy-result-{i}" data-sy-match-result></small></div>'
 return s+button('Проверить соответствия','data-sy-match-check')+'<p class="sy-feedback" role="status" data-sy-match-feedback></p></fieldset>'
def solution(text):return '<details class="sy-solution"><summary>Разобрать решение</summary>'+paras([text])+'</details>'
def labs(l):
 k=l['lab'];s=f'<section class="sy-lab" data-sy-lab="{k}" id="practice"><p class="eyebrow">Исследование</p><h2>Соберём и проверим</h2>'
 if k=='voices':
  s+=paras(['Определите, что делает каждая фраза. Вариант перевода — часть работы с текстом; личная аналогия подписывается отдельно.'])
  opts=['Сообщение о традиционной атрибуции','Вариант русского перевода','Современная личная аналогия']
  s+=match([('«Традиция приписывает… патриарху Аврааму»',opts[0],opts),('«Душа» или «человек» для нефеш',opts[1],opts),('«Мне сочетания напоминают конструктор»',opts[2],opts)])
  s+=solution('Первая фраза сообщает о традиции. Вторая показывает переводческое решение. Третья принадлежит современному читателю. Ни одна не должна незаметно подменять другую.')
 elif k=='paths':
  s+='<figure class="sy-diagram"><svg viewBox="0 0 640 265" role="img" aria-label="Пути разделены на сефирот и буквы; буквы — на матерей, двойные и простые"><g fill="none" stroke="currentColor" stroke-width="2"><path d="M320 52V76H165V103M320 76H475V103M475 145V171H345V207M475 171V207M475 171H600V207"/></g><g class="sy-diagram-label"><text x="320" y="38">Пути</text><text x="165" y="130">Сефирот</text><text x="475" y="130">Буквы</text><text x="345" y="235">Матери</text><text x="475" y="235">Двойные</text><text x="600" y="235">Простые</text></g></svg><figcaption>Линии показывают включение в ряд. Заполните числа, опираясь на Т, I:1–2.</figcaption></figure>'
  opts=['3','7','10','12','22','32'];s+=match([(a,b,opts) for a,b in [('Все пути','32'),('Сефирот','10'),('Буквы','22'),('Матери','3'),('Двойные','7'),('Простые','12')]])
  s+=solution('32 = 10 + 22; внутри буквенного ряда 22 = 3 + 7 + 12. Положение ветвей выбрано для учебной схемы, а не заимствовано как обязательный рисунок из книги.')
 elif k=='depths':
  opts=['конец','зло','низ','запад','юг'];s+=match([(a,b,opts) for a,b in [('Начало — …','конец'),('Добро — …','зло'),('Верх — …','низ'),('Восток — …','запад'),('Север — …','юг')]])
  s+=solution('Пять пар дают десять глубин. Пространственные пары: верх/низ, восток/запад, север/юг. Начало/конец и добро/зло оставляем отличными от пространственных направлений.')
 elif k=='flame':
  s+='<figure class="sy-diagram sy-flame"><svg viewBox="0 0 500 245" role="img" aria-label="Учебный образ: пламя связано с углём"><path d="M250 25C286 80 328 110 291 166C319 110 260 106 250 72C224 110 190 124 211 166C161 124 216 84 250 25" fill="#b79452"/><ellipse cx="250" cy="181" rx="73" ry="31" fill="#15343e"/><g fill="#47616a" font-size="17" text-anchor="middle"><text x="250" y="234">Пламя связано с углём</text></g></svg><figcaption>Учебная иллюстрация сравнения из Т, I:7.</figcaption></figure><fieldset disabled data-sy-enhanced><legend>Посмотрите на три уровня чтения</legend><div class="sy-actions">'+button('Слова текста','data-sy-flame="0" aria-pressed="true"')+button('Ход объяснения','data-sy-flame="1" aria-pressed="false"',True)+button('Личная аналогия','data-sy-flame="2" aria-pressed="false"',True)+'</div></fieldset><p class="sy-output" data-sy-flame-output role="status">Вокруг образа говорится о связи конца и начала и о единстве Господа.</p>'
  s+=solution('В объяснении можно отметить различимость внутри связи. Личная аналогия, например мысль и её выражение, принадлежит читателю и имеет свои границы.')
 elif k=='operations':
  s+='<p>Исходный ряд: <strong>А Б В</strong>. Выберите действие и сравните результат.</p><fieldset disabled data-sy-enhanced><legend>Действия над рядом</legend><div class="sy-actions">'+button('Поменять порядок','data-sy-operation="order"')+button('Заменить один знак','data-sy-operation="replace"',True)+button('Исходный ряд','data-sy-operation="reset"',True)+'</div></fieldset><div class="sy-letter-row" data-sy-operation-row>А Б В</div><p role="status" data-sy-operation-output>Три различных знака в исходном порядке.</p>'
  s+=solution('Ряд В Б А содержит те же знаки в другом порядке. В ряду А Б Г количество то же, но состав изменён: вместо В появился Г. Это две разные операции.')
 elif k=='pairs':
  s+='<fieldset disabled data-sy-enhanced><legend>Лаборатория пар</legend><label for="sy-pair-size">Количество различных знаков: <output for="sy-pair-size" data-sy-pair-size>4</output></label><input id="sy-pair-size" type="range" min="3" max="22" value="4"><label class="sy-check"><input type="checkbox" id="sy-pair-ordered"> Учитывать порядок: АБ и БА — разные сочетания</label></fieldset><p class="sy-formula" data-sy-pair-formula role="status">4 × 3 ÷ 2 = 6 пар</p><div class="sy-pair-list" data-sy-pair-list aria-label="Полученные пары"></div>'
  s+=solution('Для n различных знаков без повторений и без учёта порядка число пар равно n × (n − 1) / 2. При n = 22 это 231. С учётом порядка: n × (n − 1), то есть 462. Формула — математическая модель для обсуждения Т, II:4–5.')
 elif k=='permutations':
  s+='<fieldset disabled data-sy-enhanced><legend>Постройте разные порядки</legend><label for="sy-perm-size">Размер набора</label><select id="sy-perm-size"><option value="3">Три знака — 6 порядков</option><option value="4">Четыре знака — 24 порядка</option></select><div class="sy-actions" data-sy-perm-buttons></div>'+button('Начать новый порядок','data-sy-perm-next',True)+button('Очистить найденные варианты','data-sy-perm-clear',True)+'</fieldset><div class="sy-letter-row" data-sy-perm-row aria-label="Текущий порядок">…</div><p role="status" data-sy-perm-feedback>Выберите первый знак.</p><p data-sy-perm-count>Найдено 0 из 6 порядков</p><div class="sy-pair-list" data-sy-perm-found></div>'
  s+=solution('Для А, Б, В получаются АБВ, АВБ, БАВ, БВА, ВАБ, ВБА. Для четырёх знаков — 24 порядка. Кнопки показывают последовательность слева направо и используют русские учебные обозначения.')
 elif k=='mothers':
  s+=match([('Стихия алеф','воздух',['огонь','вода','воздух']),('Стихия мем','вода',['огонь','вода','воздух']),('Стихия шин','огонь',['огонь','вода','воздух']),('Мем в году','холодное',['жаркое','холодное','изобилие']),('Шин у человека','голова',['голова','чрево','тело']),('Алеф у человека','тело',['голова','чрево','тело'])])
  s+=solution('Т, III:6–8: алеф — воздух, изобилие, тело; мем — земля через воду, холодное, чрево; шин — небеса через огонь, жаркое, голова. Уравновешивание раскрывается в контексте III:1–4.')
 elif k=='opposites':
  opts=['смерть','глупость','бедность','рабство'];s+=match([(a,b,opts) for a,b in [('Жизнь — …','смерть'),('Мудрость — …','глупость'),('Богатство — …','бедность'),('Владычество — …','рабство')]])
  s+=solution('Эти пары выписаны из Т, IV:1. Перечень противоположностей ещё не заменяет подробные соответствия букв светилам в IV:5–11.')
 elif k=='compare':
  s+='<fieldset disabled data-sy-enhanced><legend>Сравните выбранную букву</legend><label for="sy-compare-letter">Буква</label><select id="sy-compare-letter">'+''.join(f'<option value="{i}">{x["letter"]} — {x["name"]}</option>' for i,x in enumerate(D['comparisons']))+'</select><div class="sy-actions">'+button('Оба текста','data-sy-witness="both" aria-pressed="true"')+button('Т — основной перевод','data-sy-witness="T" aria-pressed="false"',True)+button('Г — редакция Гра','data-sy-witness="G" aria-pressed="false"',True)+'</div></fieldset><div class="sy-comparison" data-sy-compare-output role="status"></div><details class="sy-solution"><summary>Все семь планетарных соответствий</summary><div class="sy-table-scroll"><table><caption>Учебная выписка из Т, IV:5–11, и Г, 4:8–14</caption><thead><tr><th scope="col">Буква</th><th scope="col">Т: светило</th><th scope="col">Г: светило</th><th scope="col">Параллель</th></tr></thead><tbody>'
  for x in D['comparisons']:s+=f'<tr><th scope="row"><bdi lang="he">{x["letter"]}</bdi> {x["name"]}</th><td>{x["Tplanet"]}</td><td>{x["Gplanet"]}</td><td>Т, {x["Tref"]}; <a href="https://www.sefaria.org/Sefer_Yetzirah_Gra_Version.{x["Gref"].replace(":",".")}?lang=he" target="_blank" rel="noopener noreferrer">Г, {x["Gref"]}</a></td></tr>'
  s+='</tbody></table></div></details>'
 elif k=='months':
  s+='<figure class="sy-diagram"><svg class="sy-wheel" viewBox="0 0 500 500" role="img" aria-label="Двенадцать месяцев в порядке Т, V:2, начиная с нисана"><circle cx="250" cy="250" r="177" fill="none" stroke="#d8d6ca" stroke-width="2"/>'
  for i,m in enumerate(D['months']):
   a=(i*30-90)*math.pi/180;x=250+177*math.cos(a);y=250+177*math.sin(a)
   s+=f'<circle class="sy-wheel-point {"active" if i==0 else ""}" data-sy-month-point="{i}" cx="{x:.1f}" cy="{y:.1f}" r="18"/><text x="{x:.1f}" y="{y+6:.1f}" text-anchor="middle" font-size="16">{i+1}</text>'
  s+='<text x="250" y="239" text-anchor="middle" font-size="54" lang="he" data-sy-month-letter>ה</text><text x="250" y="280" text-anchor="middle" font-size="22" data-sy-month-label>нисан</text></svg><figcaption>Порядок месяцев по Т, V:2. Начало отсчёта — нисан.</figcaption></figure><fieldset disabled data-sy-enhanced><legend>Выберите месяц</legend><div class="sy-month-buttons">'+''.join(f'<button type="button" data-sy-month="{i}" aria-pressed="{"true" if i==0 else "false"}">{i+1}. {m["month"]}</button>' for i,m in enumerate(D['months']))+'</div></fieldset><p class="sy-output" data-sy-month-output role="status">Хей — Овен — нисан. Источник: Т, V:2.</p><details class="sy-solution"><summary>Весь ряд букв, знаков и месяцев</summary><div class="sy-table-scroll"><table><caption>Т, V:2. Учебная выписка</caption><thead><tr><th>Буква</th><th>Знак</th><th>Месяц</th></tr></thead><tbody>'+''.join(f'<tr><th scope="row"><bdi lang="he">{m["letter"]}</bdi> {m["name"]}</th><td>{m["sign"]}</td><td>{m["month"]}</td></tr>' for m in D['months'])+'</tbody></table></div></details>'
 elif k=='portfolio':
  s+='<p>Проверьте свою работу по пяти вопросам. Они помогают редактировать комментарий; объём записи не оценивается автоматически.</p><ul class="sy-rubric">'+''.join('<li>'+E(x)+'</li>' for x in ['Можно ли найти отрывок по моей ссылке?','Отличены ли цитата, пояснение и личная аналогия?','Подписано ли значение каждой линии или столбца схемы?','Есть ли проверенная параллель, если я сравниваю два текста?','Назван ли предел вывода и следующий вопрос?'])+'</ul><p><a href="../notebook/">Собрать и скачать записи всех занятий →</a></p>'
 return s+'<noscript><p>Интерактивные действия доступны с JavaScript. Объяснение, решение и источники можно читать без него.</p></noscript></section>'
def source_block(l=None):
 s='<section class="sy-source" id="sources"><h2>Тексты, с которыми мы работаем</h2><h3>Т — основной русский текст</h3>'+paras([D['sources']['T']['title'],D['sources']['T']['detail']])
 if l:s+='<p><strong>В этом занятии:</strong> '+E(l['read'])+'</p>'
 s+='<h3>Г — параллели редакции Гра</h3><p><a href="'+D['sources']['G']['url']+'" target="_blank" rel="noopener noreferrer">'+E(D['sources']['G']['title'])+'</a></p>'+paras([D['sources']['G']['detail']])
 refs={7:['4:16'],10:['4:8'],11:['5:7']}.get(l['id'] if l else 0,[])
 for q in D['parallelExcerpts']:
  if l and q['ref'] not in refs:continue
  s+='<div class="sy-he-source"><p lang="he" dir="rtl">'+E(q['he'])+'</p><p>'+E(q['meaning'])+'</p><a href="https://www.sefaria.org/Sefer_Yetzirah_Gra_Version.'+q['ref'].replace(':','.')+'?lang=he" target="_blank" rel="noopener noreferrer">Г, '+q['ref']+' →</a></div>'
 s+='<p class="fine">Основной русский текст позволяет следовать главам I–VI. Для самостоятельного чтения целиком используйте указанное издание; на страницах модуля приведены короткие выписки и развёрнутые учебные пояснения. Нумерацию другой редакции нужно сверять по содержанию.</p></section>'
 return s
def notebook_controls():
 return '<div class="sy-actions">'+button('Скачать тетрадь модуля','data-sy-export')+button('Скачать записи текстом','data-sy-export-text',True)+'</div><details class="sy-solution"><summary>Перенести записи модуля</summary><p>Выберите JSON-файл, сохранённый этой тетрадью. Существующие записи сохранятся; отличающиеся тексты будут добавлены с пометкой.</p><label for="sy-import">Файл тетради «Сефер Йецира»</label><input id="sy-import" type="file" accept="application/json,.json"><p role="status" data-sy-import-status></p></details>'
def build(page,crumbs):
 b=crumbs('../../','Сефер Йецира')+'<header class="sy-hero"><p class="eyebrow">Модуль чтения · 12 занятий</p><h1>Сефер Йецира</h1><p class="sy-subtitle">Читаем, собираем схемы,<br>сравниваем редакции</p><p class="lead">У одной строки может быть несколько задач: назвать число, связать образы, предложить исследование. Будем учиться замечать их — и объяснять прочитанное своими словами.</p><div class="sy-actions"><a class="button" data-sy-resume href="book-and-reader/">Начать первое занятие →</a><a class="button secondary" href="#program">Посмотреть маршрут</a><a href="notebook/">Тетрадь модуля</a></div>'+progress()+'</header>'
 b+='<section class="sy-intro"><div><p class="eyebrow">Как устроено чтение</p><h2>От первой выписки<br>к своему комментарию</h2><p>12 занятий охватывают основные темы шести глав выбранного русского текста. В каждом есть вопрос перед чтением, короткая цитата, пояснения, упражнение и запись. Все занятия открыты; можно проходить их частями.</p><p>Ориентир — 20–35 минут на занятие, с возможностью возвращаться. Иврит заранее знать не требуется. Для общей ориентации пригодятся <a href="../sefer-yetzirah/">вводный урок о числах и буквах</a> и <a href="../letters-and-combinations/">урок о сочетаниях</a>.</p></div><div class="sy-principles"><p><strong>Читаем</strong><br>Отличаем текст, перевод и собственное объяснение.</p><p><strong>Собираем</strong><br>Подписываем, что означает каждая связь в схеме.</p><p><strong>Сравниваем</strong><br>Проверяем одинаковые и разные элементы двух конкретных строк.</p></div></section>'
 b+='<section id="program" class="section"><p class="eyebrow">Можно идти по порядку</p><h2>Двенадцать встреч с книгой</h2><div class="sy-cards">'
 for l in D['lessons']:b+=f'<article class="sy-card"><span class="sy-number">{l["id"]:02d}</span><h3><a href="{l["slug"]}/">{E(l["title"])}</a></h3><p>{E(l["aim"][0].upper()+l["aim"][1:])}</p><small data-sy-mark="{l["id"]}">Можно начать</small></article>'
 b+='</div></section><section class="sy-route-note"><h2>Как понять, что Вы продвинулись</h2><p>Вы находите отрывок по ссылке, объясняете одну связь, проверяете её по тексту и формулируете оставшийся вопрос. В конце маршрута соберёте небольшой собственный комментарий.</p><p>После занятия можно отметить его как пройденное. Вопросы для самопроверки объясняют ответ; отметку о продвижении ставите Вы.</p></section>'+source_block()+payload()
 page(BASE,D['title'],'12 занятий по Сефер Йецира: короткие цитаты, подробные объяснения, схемы, 231 врата, перестановки, сравнение редакций и тетрадь.',b)
 for l in D['lessons']:
  side='<aside class="sy-side"><details class="toc" open><summary>Занятия модуля</summary><ol>'+''.join(f'<li><a href="{link(x)}" {"aria-current=page" if x["id"]==l["id"] else ""}><span>{x["id"]:02d}</span> {E(x["title"])}</a></li>' for x in D['lessons'])+'</ol><a href="../notebook/">Мои записи →</a></details></aside>'
  b=crumbs('../../../','Сефер Йецира · '+str(l['id']))+'<p class="sy-back"><a href="../">← Весь модуль</a></p><div class="sy-shell">'+side+f'<article class="sy-lesson" data-sy-lesson="{l["id"]}"><header><p class="eyebrow">Сефер Йецира · Занятие {l["id"]} из 12</p><h1>{E(l["title"])}</h1><p class="lead">После занятия Вы сможете {E(l["aim"])}</p><p class="fine">20–35 минут; можно читать частями · <a href="#sources">Источники</a></p>'+progress()+'</header>'
  b+='<nav class="sy-lesson-steps" aria-label="Шаги занятия"><a href="#before">Первый вопрос</a><a href="#reading">Чтение</a><a href="#practice">Исследование</a><a href="#check">Самопроверка</a><a href="#reflection">Моя запись</a></nav>'
  b+=f'<section class="sy-before" id="before"><p class="eyebrow">Перед объяснением</p><h2>Сначала Ваша мысль</h2><label for="sy-before-{l["id"]}">{E(l["question"])}</label><textarea id="sy-before-{l["id"]}" data-sy-field="before" disabled data-sy-enhanced maxlength="100000" rows="3" placeholder="Можно оставить предположение или вопрос" aria-describedby="sy-save-before"></textarea><small id="sy-save-before" data-sy-saved="before" role="status"></small></section>'
  b+='<section id="reading"><p class="eyebrow">Короткая выписка</p><blockquote class="sy-quote">'+E(l['quote'])+'</blockquote><p class="sy-citation">Т — перевод И. Р. Тантлевского. '+E(l['read'])+'</p>'
  if l['id']==1:b+='<p class="fine">Эта выписка взята из вступления к переводу; это сообщение об атрибуции, а не строка основного текста.</p>'
  b+='</section>'+''.join('<section class="sy-reading"><h2>'+E(x['title'])+'</h2>'+paras(x['text'])+'</section>' for x in l['sections'])+labs(l)
  b+='<section id="check" class="sy-quiz"><p class="eyebrow">Самопроверка</p><h2>Могу ли я объяснить?</h2><p>Выберите ответ, затем откройте пояснения. Можно пробовать несколько раз.</p>'
  for i,q in enumerate(l['quiz']):
   b+=f'<fieldset disabled data-sy-enhanced><legend>{i+1}. {E(q["q"])}</legend>'+''.join(f'<label class="sy-option"><input type="radio" name="sy-q-{i}" value="{j}" data-sy-question="{i}"> <span>{E(o)}</span></label>' for j,o in enumerate(q['options']))+f'<p role="status" data-sy-q-feedback="{i}"></p></fieldset>'
  b+=button('Проверить ответы','data-sy-quiz-check')+'<p class="sy-feedback" role="status" data-sy-quiz-result></p><details class="sy-solution"><summary>Пояснения к вопросам</summary>'+''.join('<p><strong>'+str(i+1)+'. '+E(q['options'][q['answer']])+'</strong> '+E(q['why'])+'</p>' for i,q in enumerate(l['quiz']))+'</details></section>'
  b+=f'<section id="reflection" class="sy-reflection"><p class="eyebrow">После чтения</p><h2>Своими словами</h2><label for="sy-note-{l["id"]}">{E(l["reflection"])}</label><textarea id="sy-note-{l["id"]}" data-sy-field="note" disabled data-sy-enhanced maxlength="100000" rows="7" placeholder="Ваша мысль, довод или оставшийся вопрос" aria-describedby="sy-save-note"></textarea><small id="sy-save-note" data-sy-saved="note" role="status"></small><details class="sy-solution"><summary>Пример хода мысли</summary>'+paras([l['sample']])+'</details><label class="sy-check"><input type="checkbox" data-sy-done disabled data-sy-enhanced> Отмечаю занятие как пройденное</label><p class="fine">Отметка — Ваша оценка продвижения. Записи сохраняются в этом браузере. <a href="../notebook/">Открыть тетрадь и скачать копию →</a></p></section><aside class="sy-return"><h2>Вернуться позже</h2>'+paras([l['returnTask']])+'</aside>'+source_block(l)+'<nav class="sy-next" aria-label="Соседние занятия">'
  prev=D['lessons'][l['id']-2] if l['id']>1 else None;nxt=D['lessons'][l['id']] if l['id']<12 else None
  b+=(f'<a href="{link(prev)}">← {E(prev["title"])}</a>' if prev else '<a href="../">← Начало модуля</a>')+(f'<a href="{link(nxt)}">{E(nxt["title"])} →</a>' if nxt else '<a href="../notebook/">Моя тетрадь →</a>')+'</nav></article></div>'+payload(l['id'])
  page(link(l),l['title']+' — Сефер Йецира',l['aim'][0].upper()+l['aim'][1:],b)
 b=crumbs('../../../','Тетрадь Сефер Йецира')+'<header class="sy-hero"><p class="eyebrow">Личные записи</p><h1>Моя тетрадь<br><em>Сефер Йецира</em></h1><p class="lead">Первое предположение, уточнённое объяснение и вопрос, к которому хочется вернуться.</p>'+progress()+'<p>Эта тетрадь хранит записи 12 занятий модуля. Они остаются в браузере на этом устройстве. Для переноса или перед очисткой браузера скачайте копию.</p>'+notebook_controls()+'<p><a href="../">К занятиям модуля →</a> · <a href="../../notebook/">Тетрадь базового курса и Зоара →</a></p></header><section data-sy-notebook><noscript><p>Для просмотра, записи и переноса тетради включите JavaScript.</p></noscript></section>'+payload()
 page(BASE+'notebook/','Моя тетрадь — Сефер Йецира','Личные записи и прогресс 12 занятий по Сефер Йецира, экспорт и перенос на другое устройство.',b,noindex=True)
