"""Build the 888-fragment catalogue without changing the legacy guided readings."""
from pathlib import Path
from html import escape as E
import json
ROOT=Path(__file__).resolve().parents[1]

def build(page,crumbs):
 d=json.loads((ROOT/'content/readings888.json').read_text())
 sources={s['id']:s for s in d['sources']};topics={t['id']:t['title'] for t in d['topics']}
 total=len(d['readings'])
 b=crumbs('../../../','888 встреч с Зоаром')+'''<header class="hero-small catalog-hero"><p class="eyebrow">Чтение в своём темпе</p><h1>888 встреч<br><em>с Зоаром</em></h1><p class="lead">Иногда одна строка останавливает надолго. Выберите тему, найдите знакомый образ или продолжите с того места, на котором остановились.</p><p>Здесь собраны 888 коротких фрагментов из русских изданий Зоара с комментарием «Сулам». Первые 88 сопровождаются разборами и вопросами курса; ещё 800 предназначены для самостоятельного чтения рядом с книгой.</p><details class="catalog-about"><summary>Как читать эту подборку</summary><p>В выбранных изданиях слова Зоара, комментарий Йегуды Ашлага и пояснения русской редакции соседствуют. Подпись к цитате указывает именно на это издание. Она не означает, что перед нами отдельно сверенный перевод арамейского оригинала.</p><p>Откройте указанную страницу и прочитайте весь нумерованный пункт: кто говорит, о каком рассказе идёт речь, что было сказано перед этим? Встреченные представления о человеке и мире сначала стоит понять внутри самого текста. Короткая фраза не заменяет этот разговор.</p><p>Можно записать непонятное слово, свою ассоциацию или возражение. Темы каталога помогают искать; они не являются оглавлением Зоара. Число 888 обозначает объём этой подборки.</p><a href="../../books/#zohar">Сначала познакомиться с книгой →</a></details><p data-reading-progress data-reading-limit="888">Прочитано 0 из 888</p><p><a href="../#guided">88 встреч с пояснениями</a> · <a href="../../notebook/#reading-notes">Мои записи</a> · <a href="#catalog-sources">Издания и страницы</a></p></header>
<section class="catalog-controls" aria-label="Поиск и выбор фрагментов" data-catalog-controls hidden><label for="quote-search">Слово, образ или номер фрагмента</label><input class="search" id="quote-search" type="search" placeholder="Например: сердце, свет или 888" autocomplete="off"><div class="catalog-filters"><label>Тема<select id="quote-topic"><option value="all">Все темы</option>'''
 b+=''.join('<option value="'+t['id']+'">'+E(t['title'])+'</option>' for t in d['topics'])
 b+='</select></label><label>Книга<select id="quote-source"><option value="all">Все 13 изданий</option>'+''.join('<option value="'+s['id']+'">'+E(s['title'])+'</option>' for s in d['sources'])+'</select></label><label>Чтение<select id="quote-status"><option value="all">Все фрагменты</option><option value="unread">Ещё не прочитано</option><option value="read">Прочитано</option><option value="notes">Есть моя запись</option><option value="guided">С разбором курса</option></select></label></div><div class="catalog-actions"><button class="button secondary" type="button" data-quote-reset>Сбросить фильтры</button><button class="button" type="button" data-quote-next>Следующий непрочитанный</button></div></section><noscript><p>Все 888 цитат доступны ниже. Для поиска можно использовать поиск браузера. Отметки и записи работают при включённом JavaScript.</p></noscript><section id="catalog-results" tabindex="-1" aria-label="Фрагменты Зоара"><div class="catalog-count" role="status" aria-live="polite" data-quote-count>888 фрагментов</div><div class="quote-list">'
 for r in d['readings']:
  s=sources[r['sourceId']];rid=str(r['id']).zfill(2)
  src=s['url']+('#page='+str(r['page']) if s['direct'] else '')
  b+=f'<article class="quote-entry" id="reading-{rid}" data-quote-id="{r["id"]}" data-quote-topics="{" ".join(r["topics"])}" data-quote-source="{s["id"]}" data-quote-kind="{r["kind"]}"><header><span class="quote-number">{r["id"]:03d}</span><div><h2>{E(r["title"])}</h2><p class="fine">{E(s["title"])} · п. {r["paragraph"]} · страница PDF {r["page"]}</p></div><a class="quote-permalink" href="#reading-{rid}" aria-label="Ссылка на фрагмент {r["id"]}">#</a></header><blockquote>{E(r["quote"])}</blockquote><p class="quote-tags">'+E(' · '.join(topics[t] for t in r['topics']))+'</p>'
  if r['kind']=='guided':b+='<p class="quote-guided"><a href="'+E(r['href'])+'">Прочитать разбор и вопрос курса →</a></p>'
  b+=f'<details class="quote-details"><summary>Источник и моя запись</summary><p class="fine">{E(s["edition"])}. Раздел «{E(r["section"])}», нумерованный пункт {r["paragraph"]}. Файл: {E(s["file"])}. Страница {r["page"]} по счётчику PDF.</p><p><a href="{E(src)}" target="_blank" rel="noopener noreferrer">'+('Открыть страницу в PDF ↗' if s['direct'] else 'Найти книгу на сайте русского издания ↗')+'</a></p>'
  if not s['direct']:b+='<p class="fine">На сайте издания выберите книгу с указанным названием. Если PDF уже сохранён у Вас, откройте файл и перейдите к указанной странице.</p>'
  b+=f'<label class="reflection-label" for="reading-note-{r["id"]}">Моя мысль, вопрос или возражение</label><textarea class="note" id="reading-note-{r["id"]}" data-reading-note="{r["id"]}" maxlength="20000"></textarea><small role="status" data-reading-status="{r["id"]}"></small></details><label class="self-check"><input type="checkbox" data-reading-done="{r["id"]}"> Прочитано и обдумано</label></article>'
 b+='</div><p class="catalog-empty" data-quote-empty hidden>Подходящих фрагментов нет. Попробуйте другое слово или снимите один из фильтров.</p><nav class="catalog-pagination" aria-label="Страницы каталога" data-quote-pagination hidden><button type="button" class="button secondary" data-quote-prev>← Назад</button><label for="quote-page">Страница <select id="quote-page"></select></label><span data-quote-pages></span><button type="button" class="button secondary" data-quote-forward>Дальше →</button></nav></section><section class="section" id="catalog-sources"><h2>Издания и страницы</h2><p>Цитаты сверены с этими PDF. Номер страницы относится к счётчику файла; в другом издании расположение текста может отличаться. Название раздела и номер пункта помогут найти то же место.</p><ul class="catalog-source-list">'
 for s in d['sources']:b+='<li><a href="'+E(s['url'])+'" target="_blank" rel="noopener noreferrer">'+E(s['title'])+'</a><span>'+E(s['file'])+' · '+str(s['pages'])+' стр.</span></li>'
 b+='</ul><p><a href="../../books/#references">Как пользоваться ссылками на книги →</a></p></section>'
 page('/course/reading/catalog/','888 коротких цитат Зоара — каталог для чтения','888 фрагментов русских изданий Зоара с Сулам: поиск по темам и книгам, точные страницы, 88 разборов, отметки чтения и личная тетрадь.',b)
 meta=[{'id':r['id'],'title':r['title'],'group':r.get('group','catalog'),'href':r['href']} for r in d['readings']]
 (ROOT/'assets/course/readings-data.js').write_text("'use strict';\nconst READING_META="+json.dumps(meta,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')+';\n')
